### ISSUE TITLE
The function name is not obfuscated and dll is not stripped. So some interesting info is disclosed.

### ISSUE THREAD

**Issue by zhimincao** [ShiqiYu/libfacedetection#1]
MBLBPDetectMultiScale_Multiview
MBLBPDetectSingleScale
MBLBPDetectMultiScale
H:\Yu\projects\facedetect-mblbp-updated\vs\Release\libfacedetect.pdb

So it is using "Multi-Block LBP" for face detection :-)

**Comment by ShiqiYu** [comment]
You are right!
