### ISSUE TITLE
How about the recall on open datasets?,I find runing the caffe model is not so good...

### ISSUE THREAD

**Issue by allenwangcheng** [ShiqiYu/libfacedetection#103]

**Comment by ml-inory** [comment]
Here is my test result on FDDB.
![DiscROC](https://user-images.githubusercontent.com/8433542/54590475-29804280-4a63-11e9-9a17-e9b3d4d561e6.png)

**Comment by allenwangcheng** [comment]
Fddb没啥挑战性吧




| |
王程
|
|
邮箱：allenwangcheng@163.com
|

签名由 网易邮箱大师 定制

On 03/19/2019 16:23, 祈Inory wrote:

Here is my test result on FDDB.

**Comment by ml-inory** [comment]
关键是在FDDB上也没有到SOTA。。

**Comment by allenwangcheng** [comment]
估计这个模型突出特点是速度吧……




| |
王程
|
|
邮箱：allenwangcheng@163.com
|

签名由 网易邮箱大师 定制

On 03/19/2019 17:40, 祈Inory wrote:

关键是在FDDB上也没有到SOTA。。

**Comment by ml-inory** [comment]
I think so too.
