### ISSUE TITLE
Isn't it a good idea to use children's photos as a demonstration?

### ISSUE THREAD

**Issue by gangyahaidao** [ShiqiYu/libfacedetection#108]
Hi，Great work，thanks！！
In file README，use children's photos as a demonstration，I don't think it's very appropriate，It should be an adult photo

**Comment by Grabber** [comment]
@gangyahaidao, so send your photo...

**Comment by chibai** [comment]
I can't see what is the problem about showing children;s phots as face detection demo

**Comment by gangyahaidao** [comment]
OK，forget it
