### ISSUE TITLE
test time on ubuntu

### ISSUE THREAD

**Issue by XiaXuehai** [ShiqiYu/libfacedetection#109]
| ----- | ----- | ----- |----- | ----- | ----- | 
| ------ | ------ | ------ | ------ | ------ | ------ |
| _ENABLE_AVX2 | OFF | OFF |ON | ON | ON | 
|  _ENABLE_INT8_CONV | OFF  | ON | OFF | ON | ON | 
| _OPENMP | OFF | OFF |  OFF | OFF | ON | 
| time |  0.308 | 0.114| 0.059 | 0.143 | 0.140 | 

640*480的图片，好奇怪。

**Comment by ShiqiYu** [comment]
第一次函数调用会涉及初始化，耗时多一些；此外，一次函数调用的计时波动一般比较大，可以多次调用并平均。
