### ISSUE TITLE
Can any one run in python?

### ISSUE THREAD

**Issue by HongChow** [ShiqiYu/libfacedetection#114]
The caffe model is provided!
Does anyone have a python interface to tun pycaffe?

**Comment by daixiangzi** [comment]
i can provide you relevant test demo by using ssd-caffe ,https://github.com/daixiangzi/face_detection

**Comment by HongChow** [comment]
> i can provide you relevant test demo by using ssd-caffe ,https://github.com/daixiangzi/face_detection

Great Thanks， it works.

**Comment by Hsing22** [comment]
> 我可以使用ssd-caffe为您提供相关的测试演示，[https：//github.com/daixiangzi/face_detection](https://github.com/daixiangzi/face_detection)

请问您这边的跑起来的CPU或者GPU占用率是多少？

**Comment by daixiangzi** [comment]
> > 我可以使用ssd-caffe为您提供相关的测试演示，[https：//github.com/daixiangzi/face_detection](https://github.com/daixiangzi/face_detection)
> 
> 请问您这边的跑起来的CPU或者GPU占用率是多少？

on cpu is hight,bug memory is very low.i not run it on gpu.wish help you
