### ISSUE TITLE
I want an example for multiple threads 

### ISSUE THREAD

**Issue by 1997huoda** [ShiqiYu/libfacedetection#120]

**Comment by sbx19850629** [comment]
To run in multi-thread, what you need is just to suspend the other thread for some time , to wait for the first thread to complete the initialization process.

**Comment by 1997huoda** [comment]
I do not totally understand 
actually, in my mind , multiple thread is like this
`new thread`
'join'
Now my program is single thread ,and I didn't got the speed in the homepage 

> 5 ms
