### ISSUE TITLE
i5 8G笔记本内存运行很慢

### ISSUE THREAD

**Issue by BenJaminKen** [ShiqiYu/libfacedetection#121]
在VS2017和opencv4.0.0 release x64，摄像头画面分辨率640*480，执行一次人脸检测facedetect_cnn大概需要400ms，请问怎么提升速度？

**Comment by ShiqiYu** [comment]
设置编译选项为最快（看readme），降低输入图像大小（一般不需要这么大）。

BenJaminKen <notifications@github.com>于2019年3月21日 周四16:08写道：

**Comment by Happylkx** [comment]
我的i7本512*512px执行一次2000ms...

**Comment by ShiqiYu** [comment]
肯定哪里错了。你确定是release？

**Comment by Happylkx** [comment]
之前确实没开...
开了release+avx2 用readme里那张800*533的图片跑样例550ms左右正常吗
i7-6700HQ的CPU

**Comment by ShiqiYu** [comment]
不会这么慢。启用 Maximize Speed/-O2  了吗？

**Comment by Happylkx** [comment]
开了呀..没开更慢

**Comment by terrencewayne** [comment]
我也遇到了类似的问题。
我的配置是i7-7700HQ，2.8GHz；
编译配置是VS2017，release，x64，Maximize Speed/-O2；
测试图片是样例中640x480的图像循环检测，统计facedetect_cnn这个函数的耗时；
平均用时是390ms，和介绍中的差距比较大。

**Comment by ShiqiYu** [comment]
Line 41, file: src/facedetectcnn.h
