### ISSUE TITLE
ios运行很慢

### ISSUE THREAD

**Issue by frostfeng** [ShiqiYu/libfacedetection#124]
我在iphone6s手机上运行 demo中的440*293图片检测landmark耗时600ms，这个速度太慢了。

还有我使用iphone6s，输入摄像头采集的1280*720的画面，检测不出人脸。请帮看看是什么问题，谢谢。代码如下：

CVPixelBufferLockBaseAddress(img, 0);
    void *data = CVPixelBufferGetBaseAddress(img);
    int width = (int)CVPixelBufferGetWidth(img);
    int height = (int)CVPixelBufferGetHeight(img);
    OSType type = CVPixelBufferGetPixelFormatType(img);

    

    vImage_Buffer src;
    src.width = width;
    src.height = height;
    src.data = data;
    src.rowBytes = CVPixelBufferGetBytesPerRow(img);
    
    dest.width = width;
    dest.height = height;
    dest.rowBytes = width * 3;
    
    vImage_Error error = vImageConvert_BGRA8888toRGB888(&src,&dest,kvImageNoFlags);
    
    BOOL gotFace = NO;
    int *pResults = NULL;
    pResults = facedetect_cnn(pBuffer, (unsigned char *)dest.data, width, height, 440 * 3);
    printf("%d faces detected.\n", (pResults ? *pResults : 0));
    CVPixelBufferUnlockBaseAddress(img, 0);

**Comment by dpmaycry** [comment]
加入 `-O3` cppflag

**Comment by ewen1024** [comment]
@frostfeng  did you find the solution for this?   I know you already  activated the openmp  otherwise it should be over 1000ms/

**Comment by ewen1024** [comment]
@dpmaycry    HI, I guess I already activated the openmp . Did you have a test on any ios?

**Comment by ewen1024** [comment]
@dpmaycry  sry, I just misunderstood you.
Without int neon openmp o3  int   goes 1600ms ,  with   neon and int -o3 goes 100ms
but where to set the openmp?  thx

**Comment by ZpFate** [comment]
> @dpmaycry sry, I just misunderstood you.
> Without int neon openmp o3 int goes 1600ms , with neon and int -o3 goes 100ms
> but where to set the openmp? thx

can you tell me how to open int neon openmp? Thank you very much

**Comment by ShiqiYu** [comment]
you can change the header file facedetectcnn.h to enable NEON.

for gcc, flag -fopenmp can enable openmp during compiling.
