### ISSUE TITLE
ZQCNN-MTCNN与libfacedetection的对比实验

### ISSUE THREAD

**Issue by zuoqing1988** [ShiqiYu/libfacedetection#126]
一年以前使用于老师的人脸检测代码，速度很赞，但是检出率比较低，于是我立志做一个速度不低于同时精度还要超过于老师的人脸检测器。

[ZQCNN](https://github.com/zuoqing1988/ZQCNN)

最近应算法群友的邀请，将ZQCNN与libfacedetection做了一些对比，请各位品鉴。

[ZQCNN-MTCNN-vs-libfacedetection](https://github.com/zuoqing1988/ZQCNN-MTCNN-vs-libfacedetection)

**Comment by ShiqiYu** [comment]
很好的工作。MTCNN是级联结构，缺点是随着人脸数目的增加，耗时会明显增加。出于这个考虑，我采用了SSD。

**Comment by zuoqing1988** [comment]
感谢于老师的评论！

我将于老师的caffe模型转成了ZQCNN格式，在ZQCNN框架下跑320x240的输入，速度方面已经和我的MTCNN接近了。ZQCNN目前不支持winograd，如果在支持winograd的框架上跑，速度能更快。

不过从检测出的结果的概率值来看，很多脸只有0.3~0.4的概率，这离MTCNN的Onet的区分度还有较大差距。另一方面，将固定输入尺寸的ssd模型拓展到任意输入尺寸，可能会造成bbox框不准。

**Comment by yufeilongyuan** [comment]
能不能将MTCNN的图像金字塔，修改为类似SSD形式的Anchor，这样可以解决一部分问题，能给点建议或者资料吗？

**Comment by zuoqing1988** [comment]
@yufeilongyuan Pnet网络太浅，得不偿失

**Comment by yufeilongyuan** [comment]
@zuoqing1988 可以修改Pnet结构啊，不一定保持原作的。况且，这样修改后，检测非人脸目标，也会好一些。有这方面的资料吗，可以推荐下或者指导下，谢谢。

**Comment by zuoqing1988** [comment]
你可以先看看我的Pnet是啥结构

**Comment by yufeilongyuan** [comment]
@zuoqing1988 您的哪一个仓库，谢谢

**Comment by zuoqing1988** [comment]
https://github.com/zuoqing1988/ZQCNN/blob/master/model/det1-dw20-fast.zqparams

**Comment by paulchou0309** [comment]
> 能不能将MTCNN的图像金字塔，修改为类似SSD形式的Anchor，这样可以解决一部分问题，能给点建议或者资料吗？

你好 你做了这类似的操作了吗？ 我也想尝试一下

**Comment by yufeilongyuan** [comment]
@paulchou0309 最近在调教我的代码，有点小问题。已经搞出来了，没测试，不知道效果如何。

**Comment by paulchou0309** [comment]
> @paulchou0309 最近在调教我的代码，有点小问题。已经搞出来了，没测试，不知道效果如何。

能不能加个qq 请教一下 大神

**Comment by paulchou0309** [comment]
> @paulchou0309 最近在调教我的代码，有点小问题。已经搞出来了，没测试，不知道效果如何。

1280486226

**Comment by paulchou0309** [comment]
@yufeilongyuan  能不能学习一下啊 大神
