### ISSUE TITLE
How to Use Android Platform??

### ISSUE THREAD

**Issue by xiaomochen520** [ShiqiYu/libfacedetection#128]
### Why is it that after I migrated to Android, the recognition time of `keliamoniz1.jpg` in the sample image was 2800 milliseconds?

This is my CMakeList.txt:
-----
```cmake
cmake_minimum_required(VERSION 3.4.1)

SET(CMAKE_BUILD_TYPE Release)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR "aarch64")

add_definitions(-O3)

add_definitions(-D_ENABLE_INT8)
#add_definitions(-D_ENABLE_AVX2)

SET(CMAKE_C_FLAGS "$ENV{CFLAGS} -O3 -Wall")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11 -O3 -pthread")
SET(CMAKE_CXX_FLAGS_RELEASE "$ENV{CXXFLAGS} -O3 -Wall")

#set(CMAKE_C_COMPILER_ABI armeabi-v7a)

set(OPENCV_PATH /home/ww/Downloads/OpenCV-android-sdk)
set(CMAKE_VERBOSE_MAKEFILE on)

include_directories(${OPENCV_PATH}/sdk/native/jni/include)
add_library(lib_opencv STATIC IMPORTED)
set_target_properties(lib_opencv
        PROPERTIES
        IMPORTED_LOCATION ${PROJECT_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libopencv_java4.so
        )

add_library( 
        native-lib

        SHARED

        src/main/cpp/native-lib.cpp
        src/main/cpp/facedetectcnn.cpp
        src/main/cpp/facedetectcnn-floatdata.cpp
        src/main/cpp/facedetectcnn-int8data.cpp
        src/main/cpp/facedetectcnn-model.cpp
        )

find_library( 
        log-lib
        log)

target_link_libraries( 
        native-lib
        ${log-lib}
        lib_opencv
        )
```

> Android device CPU is : `mtk6737`

**Comment by dpmaycry** [comment]
try enable neon and openmp in your cmakelist
and what size(px) is the image?

**Comment by xiaomochen520** [comment]
> 尝试在你的cmakelist中启用neon和openmp 
> ，图像的大小（px）是多少？

Image Size Is (640 X 480) ，and i use `neon` and `openmp` in my cmakelist, But it doesn't work.

**Comment by dpmaycry** [comment]
Try cmakelist.txt like mine,but modify for your own path.
[CMakeLists.txt](https://github.com/ShiqiYu/libfacedetection/files/3007050/CMakeLists.txt)

**Comment by xiaomochen520** [comment]
@dpmaycry  Think you .  :+1:  :100: : -)

**Comment by Dreamgang** [comment]
@xiaomochen520 后来你的问题解决了吗？你那边能成功跑通那个安卓工程吗？我这边在编译的时候遇到一个问题，提示 R.styleable找不到位置，不知道你有没有遇到过

**Comment by Dreamgang** [comment]
@dpmaycry  could you tell me how to modify the Cmakelists.txt

**Comment by xiaomochen520** [comment]
@Dreamgang  解决了，能跑通，也没有遇到你说的问题，我没有使用 dpmaycry 提供的原版代码，我看了下他的CMakeLists.txt

**Comment by Dreamgang** [comment]
@xiaomochen520 你可以跟我说下，你是怎么跑的吗？或者你可以把你的安卓工程发我一份嘛，我想测一测他这个模型在安卓机上的运行速度情况。我的邮箱是249054793@qq.com。您看你是否方便，谢谢！

**Comment by xiaomochen520** [comment]
@Dreamgang  这个项目里面提供的不是有Android的APK么，你可以试试看。

**Comment by dpmaycry** [comment]
> @xiaomochen520 后来你的问题解决了吗？你那边能成功跑通那个安卓工程吗？我这边在编译的时候遇到一个问题，提示 R.styleable找不到位置，不知道你有没有遇到过

Follow the readme of android. In my opinion, can't find R.styleable due to opencv integration.

**Comment by howieraem** [comment]
> > @xiaomochen520 后来你的问题解决了吗？你那边能成功跑通那个安卓工程吗？我这边在编译的时候遇到一个问题，提示 R.styleable找不到位置，不知道你有没有遇到过
> 
> Follow the readme of android. In my opinion, can't find R.styleable due to opencv integration.

Hi, I'm new to android. I did what you suggested in README

> 3. import OpenCV-android-sdk/sdk/java to this porject as a module so android can use it

in android studio, but it said it couldn't find opencvlibrary401. If I manually copy OpenCV-android-sdk/sdk/java to the opencvlibrary401 directory, the R.styleable not resolved error occurred. Could you please give me a bit more instructions?
