### ISSUE TITLE
我用VS2017运行失败，以下是输出和错误，请大家指点下。

### ISSUE THREAD

**Issue by lunchben** [ShiqiYu/libfacedetection#129]
1>------ 已启动全部重新生成: 项目: ld, 配置: Debug x64 ------
1>libfacedetect.cpp
1>d:\libfacedetection-master\example\libfacedetect.cpp(134): warning C4018: “>=”: 有符号/无符号不匹配
1>libfacedetectcnn-example.cpp
1>facedetectcnn-floatdata.cpp
1>facedetectcnn-int8data.cpp
1>facedetectcnn-model.cpp
1>d:\libfacedetection-master\src\facedetectcnn-model.cpp(548): warning C4101: “t”: 未引用的局部变量
1>facedetectcnn.cpp
1>正在编译...
1>正在生成代码...
1>  正在创建库 E:\visual studio2017\workplace\ld\x64\Debug\ld.lib 和对象 E:\visual studio2017\workplace\ld\x64\Debug\ld.exp
1>libfacedetect.obj : error LNK2019: 无法解析的外部符号 __imp_gst_base_transform_get_type，该符号在函数 "void __cdecl face_detect_class_init(struct FaceDetectClass *)" (?face_detect_class_init@@YAXPEAUFaceDetectClass@@@Z) 中被引用
1>libfacedetect.obj : error LNK2019: 无法解析的外部符号 __imp_gst_video_info_from_caps，该符号在函数 "int __cdecl set_caps(struct _GstBaseTransform *,struct _GstCaps *,struct _GstCaps *)" (?set_caps@@YAHPEAU_GstBaseTransform@@PEAU_GstCaps@@1@Z) 中被引用
1>E:\visual studio2017\workplace\ld\x64\Debug\ld.exe : fatal error LNK1120: 2 个无法解析的外部命令
1>已完成生成项目“ld.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

**Comment by Happylkx** [comment]
你的lib是x86的吧

**Comment by Dreamgang** [comment]
你好，我也遇到这个问题了，请问你后来解决了吗？

**Comment by W-CQ** [comment]
您好，这个问题最终是怎么解决的呢，求一个解决办法~

**Comment by ShiqiYu** [comment]
这个是缺少依赖的库导致。
