### ISSUE TITLE
Could not compile the source file

### ISSUE THREAD

**Issue by esimov** [ShiqiYu/libfacedetection#131]
OS: Ubuntu 16.04

I was trying different solutions, but none of them worked. First I tried with the compiler included in `aarch64-toolchain.cmake`, but since on my environment `gcc-linaro` it is not installed I've replaced it with the default gcc. The `make` ran this time successfully, however when i tried to run the example I was getting the following error:

`libfacedetection/src/facedetectcnn.h:58:22: fatal error: arm_neon.h: No such file or directory`

Is there a working solution for making the example to work? It would be great a detailed description.

**Comment by universeroc** [comment]
What I do is just try to copy the source file into your project and build them directly and it works, just make sure the source file include relative path, a little modification. It's not too hard to make it work.

**Comment by ShiqiYu** [comment]
Since the code doesn't depend on any other libraries, you can just take the
code as written by yourself.

**Comment by feiliuzhixia1000m** [comment]
if you compile the code on your PC, it's gcc is based on X86, neon.h is for arm, so you need a cross compiler.
Good luck
