### ISSUE TITLE
some advises(一些建议）

### ISSUE THREAD

**Issue by jsxyhelu** [ShiqiYu/libfacedetection#134]
If this lib want's to be more popular,a compare beyound opencv、dlib is needed。If professor want to do this work,I may be helpful。
这是一个很好的算法库，但是我认为如果想让它更流行的话，做一些关于opencv和dlib的比较是非常必要的，否则我们对于这个库的了解还很肤浅。如果于教授准备做这个工作，我也许可以起到一些帮助。

**Comment by ShiqiYu** [comment]
谢谢，后面会将模型加入到OpenCV中。
