### ISSUE TITLE
OpenVino Plugin missing

### ISSUE THREAD

**Issue by mdv3101** [ShiqiYu/libfacedetection#136]
I think the openvino model provided will need some plugins for the custom implementation. 
Can you share a .py or a .cpp to test the same.

Regards.

**Comment by ShiqiYu** [comment]
I will, thank you for mentioning that.

Madhav Agarwal <notifications@github.com>于2019年4月1日 周一15:45写道：

**Comment by mdv3101** [comment]
@ShiqiYu 
Are you planning to release this ?

**Comment by mdv3101** [comment]
@ShiqiYu 
Any update ?

**Comment by ShiqiYu** [comment]
You can use the ssd detection sample in OpenVINO to load this model can do
face detection.

Madhav Agarwal <notifications@github.com>于2019年5月30日 周四11:04写道：

**Comment by mdv3101** [comment]
OK.
