### ISSUE TITLE
where is the code to resize the input image to specific shape just same as prototxt？

### ISSUE THREAD

**Issue by BT123** [ShiqiYu/libfacedetection#138]
Is the model you used to detect faces in images same as the caffe/tengine model in ./models? 
The models  need an image which shape is (320,240), but I don't find any code to resize the input image to the specific size.
Can Dr. Yu give me some advise?
Thank you!

**Comment by feiliuzhixia1000m** [comment]
I have the same question。

**Comment by XuejianLiu** [comment]
resize(image, image, Size(320,240));

**Comment by HosseynGT** [comment]
> resize(image, image, Size(320,240));
check
line 138 in yu_facedetection.cpp

cv::resize(img, resize_img, cv::Size(img_w, img_h), 0, 0,cv::INTER_NEAREST);
