### ISSUE TITLE
error encountered when enable _ENABLE_AVX2

### ISSUE THREAD

**Issue by LinGeLin** [ShiqiYu/libfacedetection#139]
I am working a Qt project on windows. I noticed the annotations：
```
//#define _ENABLE_AVX2 //Please enable it if X64 CPU
//#define _ENABLE_NEON //Please enable it if ARM CPU
```
So， I tried to enable _ENABLE_AVX2 .These are the mistakes I have encountered.

```
error: C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换
error: C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换
error: C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换
error: C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换
```

How can I solve it？

**Comment by LinGeLin** [comment]
there are some differences between <immintrin.h>of vs and <immintrin.h>of Qt. How can fixed it.

**Comment by Happylkx** [comment]
Select x64 when using CMake to build the project.

**Comment by ShiqiYu** [comment]
It seems your development platform cannot support AVX2. Visual Studio should work well with AVX2. It's strange. You can try the new source code now.
