### ISSUE TITLE
Strange behaviour when called in multithreading ~ Detection not working

### ISSUE THREAD

**Issue by kafan1986** [ShiqiYu/libfacedetection#140]
UPDATE: I have started to check the multi threaded implementation with actual image, although no error are thrown but it does not detect any faces. So, reason for faster processing might be linked to no detection or processing at all.

I am building for android and when I run detection from a single thread the time taken is 140ms but when detection is done in multi threaded environment (called from 2 threads independently) that time taken for each detection halves to around 70ms, expected behaviour would be that the detection time per thread remains same i.e. 140 ms. Why is this library performing such behaviour? 

I have double checked my code, the Mat Size and every other parameter remains exactly same , strangely it actually halves detection time per thread (tested with 2 parallel threads till now).

**Comment by Happylkx** [comment]
你好，请问问题解决了吗，我也遇到了同样的问题..

**Comment by kafan1986** [comment]
> 你好，请问问题解决了吗，我也遇到了同样的问题..

No. The repo owner never replied back on the issue. I reverted to using the single thread detection for my use case. If you want a faster detection and your hardware has multiple cores, then you can enable openmp. For me the single thread non-openmp version was detecting in around 180 ms (CPU usage was less than 15-20% only single core)  and openmp was detecting in 110 ms (but CPU usage became 4x i.e. around 60-70%)

**Comment by ShiqiYu** [comment]
You can enable OpenMP to speedup. Sorry for the later reply.
