### ISSUE TITLE
如何将一个深度学习模型转化为c++代码?

### ISSUE THREAD

**Issue by xmduhan** [ShiqiYu/libfacedetection#142]
请教是如何将一个深度学习模型转化为c++代码的? 我们有很多模型在产品化的过程中十分需要这样的方式! 谢谢!

**Comment by nuanxinqing** [comment]
同问！很有兴趣了解

**Comment by xiaozhuka** [comment]
把每层的权重按照指定格式保存到文件中就好啦，直接写成cpp文件

**Comment by ShiqiYu** [comment]
yes

**Comment by xmduhan** [comment]
@xiaozhuka 
能说的详细些吗？有现成工具可使用，还是要自己编写转化程序？

**Comment by XuejianLiu** [comment]
于老师把权重保存成源文件中的静态变量了，我有个疑问，如果是更大的model呢，有更多的参数，是当静态变量保存进cpp文件，还是保存成.dat文件，读取好呢

**Comment by doublegssc** [comment]
同问！！很需要，可以说的详细一些吗？@xiaozhuka

**Comment by ShiqiYu** [comment]
后面我会共享我的训练的Pytorch代码，里面有导出cpp文件的功能。

**Comment by xmduhan** [comment]
非常期待
