### ISSUE TITLE
运行demo报错，非法指令 (核心已转储）

### ISSUE THREAD

**Issue by Quitino** [ShiqiYu/libfacedetection#144]
于老师您好，运行到facedetection-model.cpp中faces = objectdetect_cnn(rgb_image_data, width, height, step);这里的时候就报错。您知道是什么愿意引起的吗？

**Comment by Quitino** [comment]
运行到facedetection-model.cpp中`faces = objectdetect_cnn(rgb_image_data, width, height, step);`这里的时候就报错。

**Comment by Quitino** [comment]
```
    std::vector<FaceRect> faces;
    faces.clear();

    faces = objectdetect_cnn(rgb_image_data, width, height, step);
```

**Comment by ShiqiYu** [comment]
这个问题是C++ vector导致，已经改为指针，现在没问题了。
