### ISSUE TITLE
About facedetectcnn-floatdata.cpp and facedetectcnn-int8data.cpp

### ISSUE THREAD

**Issue by dssone** [ShiqiYu/libfacedetection#146]
Professor :
Thanks for your opening code, and i have a question about facedetectcnn-floatdata.cpp. How did you get the data in this file?  Do you have some tools to extract data from  yufacedetectnet-open-v1.caffemodel to facedetectcnn-floatdata.cpp ?

**Comment by ewen1024** [comment]
For this, find a python script to copy the parameters from caffemodel, they are just the same as floatdata.cpp. 
My question is how to get the int8data?

**Comment by ShiqiYu** [comment]
@dssone @ewen1024 I will realse my new pytorch training source code. The source code for converting to CPP will be inside.
