### ISSUE TITLE
请问，在树莓派上g++为何编译不出来？

### ISSUE THREAD

**Issue by 792301982** [ShiqiYu/libfacedetection#147]
命令：
g++ libfacedetectcnn-example.cpp  -O3 `pkg-config --cflags opencv`  `pkg-config --libs opencv` 

报错：
/tmp/ccaQUCQ3.o：在函数‘main’中：
libfacedetectcnn-example.cpp:(.text.startup+0x94)：对‘facedetect_cnn’未定义的引用
collect2: error: ld returned 1 exit status

**Comment by 792301982** [comment]
src 目录下的文件 已经 都复制过来了。

**Comment by xiaozhuka** [comment]
未定义的引用一般是链接错误，你没有编译其他的cpp文件

**Comment by 792301982** [comment]
> 未定义的引用一般是链接错误，你没有编译其他的cpp文件

感谢大佬，已经解决了

**Comment by XuejianLiu** [comment]
@792301982 你好，我之前没怎么用过树莓派，也是想把libfacedetection移植到树莓派上，方便把你在树莓派上用g++编译libface的过程开源下吗？十分感谢！
