### ISSUE TITLE
Does this library on android need BGR Mat or Gray Scale Mat?

### ISSUE THREAD

**Issue by kafan1986** [ShiqiYu/libfacedetection#148]
Hello,

Please answer the following questions:
a) Does this library need BGR Mat (3 channels) only or Gray scale Mat (1 channel) also works? I am confused because the example mentions the following grayscale whereas android example shows BGR Mat usage.
https://github.com/ShiqiYu/libfacedetection/blob/6bfdf425320ad7221a52d9a1d15c03be8d749e3b/example/libfacedetectcnn-example.cpp#L55

b) If Gray Scale is also supported, how much face detection accuracy is lost when compared to BGR?

**Comment by ShiqiYu** [comment]
Now only GBR is supported.
