### ISSUE TITLE
您好，请教下，运行速度问题

### ISSUE THREAD

**Issue by yw2278** [ShiqiYu/libfacedetection#154]
我在Xeon(R) CPU E7-4820 v4 @ 2.00GHz单核模式跑408*240的图片，单张的运行时间在0.5s，可以请教下怎么提升速度么？

**Comment by ShiqiYu** [comment]
- Please add -O3 to turn on optimizations when you compile the source
   code using g++.
   - Please choose 'Maximize Speed/-O2' when you compile the source code
   using Microsoft Visual Studio.

**Comment by yw2278** [comment]
谢谢您我试试

**Comment by w8501** [comment]
> 谢谢您我试试
请问你这个运行速度优化成功了吗

**Comment by GreenTeaHua** [comment]
速度较慢，成功没有？

**Comment by QianYC** [comment]
我是i7-8550u，加了-O3后，从100ms的级别降到了10ms的级别
