### ISSUE TITLE
单人脸图片检测出多个人脸

### ISSUE THREAD

**Issue by zoushipeng** [ShiqiYu/libfacedetection#156]
![image](https://user-images.githubusercontent.com/19241583/58676836-4ce13b00-838c-11e9-82f2-9609daafae2f.png)
有部分照片检测算法检出多个人脸，图片来源LFW

**Comment by zoushipeng** [comment]
![Abdullah_al-Attiyah_0003](https://user-images.githubusercontent.com/19241583/58677165-7e0e3b00-838d-11e9-8995-ecbbbde1f323.jpg)
![Aaron_Pena_0001](https://user-images.githubusercontent.com/19241583/58677173-8c5c5700-838d-11e9-8230-0dff582d85e7.jpg)
原图

**Comment by zoushipeng** [comment]
通过简单测试，可用置信度进行过滤，大部分检测出多张照片但是实际无人脸的，置信度一般低于60，综合实际情况，可设置过滤阈值为70，已过滤此类情况。

**Comment by yongxiangzheng** [comment]
你好，我这边测试单人脸检测结果多人脸，有两个位置置信度都高，但是位置都错误，似乎用阈值过滤也是没有用。
测试人脸：
![微信截图_20190709140609](https://user-images.githubusercontent.com/8653159/60863398-2cda4c80-a253-11e9-8e93-50f988de9d20.png)
程序运行结果：
![微信截图_20190709141208](https://user-images.githubusercontent.com/8653159/60863531-9ce8d280-a253-11e9-91e6-6efdbbe5a019.png)

人脸原图：
![Tom_Cruise_avp_2014_4](https://user-images.githubusercontent.com/8653159/60863544-a7a36780-a253-11e9-838a-f1d50dd53838.jpg)

**Comment by zoushipeng** [comment]
可以尝试用图片进行resize，我这边按照将最大边压缩未480像素，可以得到正常的结果。这个应该是跟训练算法采用的图片和参数有关。
![image](https://user-images.githubusercontent.com/19241583/60864029-fe5d7100-a254-11e9-9d66-a44b6da7c229.png)

**Comment by ShiqiYu** [comment]
是的，训练图像最大边是320

**Comment by yongxiangzheng** [comment]
好的，那我明白了，谢谢老师们的解答。
