### ISSUE TITLE
于老师您好，我想问下在调用caffemodel做推理的时候出现错误是什么原因引起的

### ISSUE THREAD

**Issue by yw2278** [ShiqiYu/libfacedetection#159]
check failed: num_priors_ * num_loc_classes_ * 4 == bottom[0]->channels() (105520 vs. 17680) Number of priors must match number of location predictions.

**Comment by ShiqiYu** [comment]
是使用我提供的模型出这个错误？你用哪个版本caffe？

yw2278 <notifications@github.com>于2019年6月26日 周三18:35写道：

**Comment by yw2278** [comment]
我用的是caffe 1.0

**Comment by yw2278** [comment]
我用的就是yufacedetectnet-open-v1这个caffe

**Comment by ShiqiYu** [comment]
应该是SSD的prioxbox定义不一致导致，可以使用Nvidia Caffe，速度更快。
https://github.com/NVIDIA/caffe/

**Comment by yw2278** [comment]
好的我试试，谢谢您
