### ISSUE TITLE
于老师你您好想请教下caffemodel的训练问题

### ISSUE THREAD

**Issue by yw2278** [ShiqiYu/libfacedetection#161]
我现在用widerface数据集做训练，训练了5w多步，loss感觉跳动比较大，似乎没有收敛，您这有什么建议么，麻烦了
![image](https://user-images.githubusercontent.com/22030956/60313945-74c7bc80-9993-11e9-8b18-ed51e6ca5cf7.png)

**Comment by ShiqiYu** [comment]
那个模型不好训练；我后面会发布pytorch的版本。
