### ISSUE TITLE
angle是否表示人脸姿态的欧拉角？

### ISSUE THREAD

**Issue by Tomhouxin** [ShiqiYu/libfacedetection#163]
于老师，您的检测结果有个angle= p[5], 这个angle本身表示的含义是什么呢，
for (int i = 0; i < num_faces; i++)
    {
        short * p = ((short*)(result_buffer + 4)) + 142 * i;
        p[0] = (short)faces[i].x;
        p[1] = (short)faces[i].y;
        p[2] = (short)faces[i].w;
        p[3] = (short)faces[i].h;
        p[4] = (short)(faces[i].score * faces[i].score * 100);
    }
但实际上没有p[5]，是否还属于待做状态？
最后感谢于老师

**Comment by ShiqiYu** [comment]
待做

**Comment by ShiqiYu** [comment]
刚发布的新版本可以检测5个关键点了。@Tomhouxin
