### ISSUE TITLE
int8 轉換

### ISSUE THREAD

**Issue by steveyeh** [ShiqiYu/libfacedetection#166]
請問作者是用什麼工具進行 caffe model int8 轉換？

**Comment by ShiqiYu** [comment]
自己写的

steveyeh <notifications@github.com>于2019年7月19日 周五10:33写道：

**Comment by steveyeh** [comment]
請問 ShiqiYu, 有做統計校正嗎？  還是直接算 min/max 量化？

**Comment by ShiqiYu** [comment]
直接乘上一个系数，使得取值范围在[-128, 127]之间。

**Comment by louielu1027** [comment]
于老师，这个int8转换的工具能开源吗？谢谢

**Comment by ShiqiYu** [comment]
> 于老师，这个int8转换的工具能开源吗？谢谢

https://github.com/ShiqiYu/libfacedetection.train/blob/master/tasks/task1/exportcpp.py
