### ISSUE TITLE
您好，想请教，我用caffemodel训练的结果现在loss在3,4,5之间跳动，这个正常么

### ISSUE THREAD

**Issue by yw2278** [ShiqiYu/libfacedetection#168]

**Comment by Linzaer** [comment]
我的结果也差不多

**Comment by yw2278** [comment]
> 我的结果也差不多
而且我训练的模型在小脸上检测结果不是很好，你也这样么

**Comment by Linzaer** [comment]
十几万次迭代也在3到5左右，loss下不去我觉得和网络本身比较浅、注重轻量化以及widerface训练集中含有大量尺度非常小的人脸有关，可以把widerface里面非常小的人脸去除训练。

ssd由于受限于尺度选择问题，小物体不占优势。小人脸检测的话，预测的时候把输入尺寸放大就可以了，比如缩放到640*480，但是速度会变慢，误报会变大。

**Comment by yw2278** [comment]
我把小于20*20的去掉了，loss降到2,3左右也还可以

**Comment by Linzaer** [comment]
是的，faceboxes 训练是去除的。

**Comment by Linzaer** [comment]
对了，你训练的时候GPU负载高吗？我尝试了多卡、NVCAFFE、原版CAFFE、加大batchsize，但是GPU负载都很低，在0到30%之间，训练卡是RTX2070，IO基本空载，cpu在67%左右，内存消耗也不大。

**Comment by yw2278** [comment]
我也是这个情况，基本上20w步3天才训完，用的是v100

**Comment by Linzaer** [comment]
嗯，应该是数据预处理部分cpu耗时，gpu空载

**Comment by yw2278** [comment]
我在FDDB上map在0.86左右，你效果怎么样

**Comment by Linzaer** [comment]
我没测fddb，我测了widerface，原模型resize到1600 单尺度 0.573/0.561/0.399 ,训练了一版1600单尺度在0.706/0.682/0.529

**Comment by fire717** [comment]
@yw2278 @Linzaer 问下训练的代码在哪呢？仓库里没看到，readme里也没。是删除了吗？

**Comment by Linzaer** [comment]
@fire717 作者给了solver、train文件就可以训练了啊

**Comment by ShiqiYu** [comment]
记得用nvidia caffe训练

linzai <notifications@github.com>于2019年8月9日 周五23:25写道：

**Comment by Linzaer** [comment]
@ShiqiYu 您好！我想问一下我用nvidia caffe训练同样的网络和数据，训练速度的确比原版caffe快，但是十几万次迭代后loss始终在9左右下不去，原版caffe的训练loss可以快速下降到3左右，这有可能是什么原因？期待您的回复。

**Comment by fire717** [comment]
> @fire717 作者给了solver、train文件就可以训练了啊

好的谢谢大佬

**Comment by ShiqiYu** [comment]
@Linzaer 我现在用Pytorch了。
