### ISSUE TITLE
关于arm板速度和多线程

### ISSUE THREAD

**Issue by fire717** [ShiqiYu/libfacedetection#171]
老师您好，有两个问题请教

1.参考您readme.md的资料，在 ARM Linux (Raspberry Pi 3 B+)上单线程cnn (CPU, 160x120) |速度为27.42ms，但是我运行您的安卓demo，这个分辨率平均60多ms，是哪设置不对吗？（使用tengine倒是速度在20多ms，但是您这里应该是没用tengine的吧？）

2.多线程实现思路能否解释下呢？如果是单个图片，其模型预测前向传播应该是串行的，无法多线程吧？如果是多个图片并行多线程，这个速度又指什么呢？谢谢！

**Comment by ShiqiYu** [comment]
打开OpenMP应该可以明显提速
