### ISSUE TITLE
提供一个python接口

### ISSUE THREAD

**Issue by armstrong1972** [ShiqiYu/libfacedetection#173]
非常感谢于老师的开源，这个版本真的很厉害，几乎所有角度的人脸都能识别。
但目前返回的结果中，还没有：角度 和 68特征点 数据，期待于老师的新版本。

本人正在学习python，所以在于老师这个版本基础上做了一个DLL接口，并用python调用测试成功。参见：https://github.com/armstrong1972/pySample-for-ShiqiYu

这是我第一次发布github项目，如果您觉得对您有帮助，帮我点个星。
（借于老师宝地做个小广告）

**Comment by ShiqiYu** [comment]
Thank you for the contribution
