### ISSUE TITLE
Any chance of FaceDetection Library for Linux ? 

### ISSUE THREAD

**Issue by suman-19** [ShiqiYu/libfacedetection#174]
I am looking for the old implementation of libFaceDetection... i am looking for a lightweight solution. So if possible can you release the .so file library for linux ? Its been 2 years since the code was released first time. 

Thanks.

**Comment by suman-19** [comment]
@ShiqiYu

**Comment by ShiqiYu** [comment]
Sorry I cannot because of some issues.
