### ISSUE TITLE
 Process finished with exit code 139 (interrupted by signal 11: SIGSEGV).?

### ISSUE THREAD

**Issue by JiaoPaner** [ShiqiYu/libfacedetection#179]
when I run the example.cpp it showed Process finished with exit code 139 (interrupted by signal 11: SIGSEGV). 
then  I debuged the line :
//!!! The input image must be a BGR one (three-channel) instead of RGB
//!!! DO NOT RELEASE pResults !!!
pResults = facedetect_cnn(pBuffer,(image.ptr<uchar>(0)), image.cols, image.rows, (int)image.step);

but I can't find the implemention of facedetect_cnn?

**Comment by JiaoPaner** [comment]
sorry .I find it in facedetectcnn-model.cpp . but it still has this error.

**Comment by ShiqiYu** [comment]
Can you debug it in the debug mode?

**Comment by JiaoPaner** [comment]
> Can you debug it in the debug mode?
I found the line as follow which maybe has errors and added "printf" to check the line.

`
/***************CONV1*********************/
....
TIME_START;
printf("--------------START--------------\n");
maxpooling2x2S2(pConvDataBlobs + convidx, &pool1);
printf("--------------END--------------\n");
TIME_END("pool1");`

then I run the app again , the results like this:
`PS C:\programing\projects\c++\facetest\x64\Release> .\facetest.exe .\test.jpg
--------------START--------------
PS C:\programing\projects\c++\facetest\x64\Release>`
why.

**Comment by JiaoPaner** [comment]
In facedetectcnn.cpp I commented the lines "#elif defined(_ENABLE_AVX2) for{...}" which in the function "maxpooling2x2S2". Run app again ,it work.
Em........  but I don't defined "_ENABLE_AVX2" .

**Comment by ShiqiYu** [comment]
If so, you can remove AVX2 code in maxpooling. I will check it later. Thank
you.
