### ISSUE TITLE
crash when run example

### ISSUE THREAD

**Issue by zhanwei** [ShiqiYu/libfacedetection#180]
commit 2a28111f3963f0cbb3806b95d01dcafcf5cc150a (HEAD -> master, origin/master, origin/HEAD)

mkdir x64
cd x64
cmake     -DENABLE_AVX2=ON     -DCMAKE_BUILD_TYPE=DEBUG     -DDEMO=ON      ..
make -j8
I got below error

mxj@mxj-Precision-Tower-3620:~/work/libfacedetection/x64$ gdb ./fdt_demo 
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./fdt_demo...done.
(gdb) r ../images/chloecalmon.png
Starting program: /home/mxj/work/libfacedetection/x64/fdt_demo ../images/chloecalmon.png
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000555555571879 in _mm256_store_si256(long long __vector(4)*, long long __vector(4)) (__A=..., __P=0x7fffffffce90) at /usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:915
915	  *__P = __A;
(gdb) bt
#0  0x0000555555571879 in _mm256_store_si256(long long __vector(4)*, long long __vector(4)) (__A=..., __P=0x7fffffffce90) at /usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:915
#1  0x0000555555571879 in dotProductUint8Int8(unsigned char*, signed char*, int, int) (p1=0x7fffeb0d1100 "", p2=0x55555589a800 "\337\332\371\333\301\275\343\333\327BA=PiK8:\\\341\335\340\323\335\316\342\342", <incomplete sequence \351>, num=27, lengthInBytes=32) at /home/mxj/work/libfacedetection/src/facedetectcnn.cpp:129
#2  0x000055555556e928 in convolution1x1P0S1(CDataBlob<unsigned char> const*, Filters const*, CDataBlob<int>*) (inputData=0x7fffffffd290, filters=0x555555873f40 <param_pFilters>, outputData=0x7fffffffd190) at /home/mxj/work/libfacedetection/src/facedetectcnn.cpp:159
#3  0x000055555556f1a3 in convolution(CDataBlob<unsigned char>*, Filters const*, CDataBlob<int>*) (inputData=0x7fffffffd290, filters=0x555555873f40 <param_pFilters>, outputData=0x7fffffffd190)
    at /home/mxj/work/libfacedetection/src/facedetectcnn.cpp:323
#4  0x000055555556f256 in convolution_relu(CDataBlob<unsigned char>*, Filters const*, CDataBlob<unsigned char>*) (inputData=0x7fffffffd290, filters=0x555555873f40 <param_pFilters>, outputData=0x7fffffffd800) at /home/mxj/work/libfacedetection/src/facedetectcnn.cpp:338
#5  0x000055555556a77a in objectdetect_cnn(unsigned char*, int, int, int) (rgbImageData=0x7fffeb597040 "\337\331\377\330\327\377\332\334\372\333\342\366\327\342\360\325\337\360\336\341\375\335\334\376\335\327\377\343\332\377\342\330\374\347\334\374\345\333\371\350\335\376\343\327\377\343\327\377\336\330\377\331\322\377\341\330\377\341\322\377\347\324\377\345\316\377\350\320\377\345\317\377\345\320\377\340\316\377\337\316\377\332\313\377\341\320\377\337\313\377\345\312\377\344\306\377\346\310\377\346\311\377\345\313\377\346\316\377\347\317\377\344\320\377\342\316\377\341\322\377\340\324\377\334\322\377\333\322\377\335\323\377\335\320\377\340\325\377\337\322\377\336\327\377\330\324\375\336\335\377\331\327\377\333\326\377\336\323\377\340\324\377\342\330\377\336\334\377\330\334\370\330\343\367\330\342\364\331\342\360\334\341\360\341\345\360\334\343\354\336\345\356\334\341\360\334\342\357\336", <incomplete sequence \343>..., width=1265, height=493, step=3795)
    at /home/mxj/work/libfacedetection/src/facedetectcnn-model.cpp:210
#6  0x000055555556be76 in facedetect_cnn(unsigned char*, unsigned char*, int, int, int) (result_buffer=0x7ffff7fd4010 "", rgb_image_data=0x7fffeb597040 "\337\331\377\330\327\377\332\334\372\333\342\366\327\342\360\325\337\360\336\341\375\335\334\376\335\327\377\343\332\377\342\330\374\347\334\374\345\333\371\350\335\376\343\327\377\343\327\377\336\330\377\331\322\377\341\330\377\341\322\377\347\324\377\345\316\377\350\320\377\345\317\377\345\320\377\340\316\377\337\316\377\332\313\377\341\320\377\337\313\377\345\312\377\344\306\377\346\310\377\346\311\377\345\313\377\346\316\377\347\317\377\344\320\377\342\316\377\341\322\377\340\324\377\334\322\377\333\322\377\335\323\377\335\320\377\340\325\377\337\322\377\336\327\377\330\324\375\336\335\377\331\327\377\333\326\377\336\323\377\340\324\377\342\330\377\336\334\377\330\334\370\330\343\367\330\342\364\331\342\360\334\341\360\341\345\360\334\343\354\336\345\356\334\341\360\334\342\357\336", <incomplete sequence \343>..., width=1265, height=493, step=3795)
    at /home/mxj/work/libfacedetection/src/facedetectcnn-model.cpp:493
#7  0x0000555555568191 in main(int, char**) (argc=2, argv=0x7fffffffdd28) at /home/mxj/work/libfacedetection/example/libfacedetectcnn-example.cpp:145

**Comment by zhanwei** [comment]
the cpu not support avx2. it is noe a bug

**Comment by zhanwei** [comment]
the cpu support avx2 confirmed

**Comment by zhanwei** [comment]
when open avx2 ,the application will crash.
disable it . the application is normal.

**Comment by ShiqiYu** [comment]
The problem should be solved. Please use the new updated source code.

**Comment by pppoe** [comment]
I got the same error with the up-to-date code...
