### ISSUE TITLE
多线程问题 

### ISSUE THREAD

**Issue by heshunchao** [ShiqiYu/libfacedetection#181]
多线程调用facedetect_cnn不成功，老师能否写一个demo？谢谢

**Comment by steveyeh** [comment]
Hi, 
A workable suggestion is to wrap facedetect_cnn as a class, then create an instance for each thread.

**Comment by ShiqiYu** [comment]
> 多线程调用facedetect_cnn不成功，老师能否写一个demo？谢谢

建议你先调用一次facedetect_cnn，然后再多线程。第一次调用facedetect_cnn会初始化一些参数，所以在多线程环境里会导致问题。

**Comment by ShiqiYu** [comment]
> Hi,
> A workable suggestion is to wrap facedetect_cnn as a class, then create an instance for each thread.

Thank you for this suggestion. I will consider it.

**Comment by heshunchao** [comment]
> > 多线程调用facedetect_cnn不成功，老师能否写一个demo？谢谢
> 
> 建议你先调用一次facedetect_cnn，然后再多线程。第一次调用facedetect_cnn会初始化一些参数，所以在多线程环境里会导致问题。

谢谢老师

**Comment by ctwlty** [comment]
为什么不提供一个init接口呢

**Comment by ShiqiYu** [comment]
@ctwlty 按说增加一个init更合理，但一个函数才是最简洁的。
