### ISSUE TITLE
关于v2版本新模型的改进优化疑问

### ISSUE THREAD

**Issue by Linzaer** [ShiqiYu/libfacedetection#182]
@ShiqiYu 于老师您好，感谢您开源了最新的caffe v2版本模型，测试了一下小人脸检测相比之前增强了不少，我对比了一下v1版本，发现改动主要有：

1. 浅层的几个3*3kernel翻倍了channel数量，翻倍了宽度，我猜想是相比于v1版本想进一步增强主干的提取特征能力和小感受野小目标的检测能力
2. 发现readme中将minsize 人脸尺寸改为了10x10,猜测widerface训练集是否从原来过滤12x12以下尺寸的人脸放宽到过滤s掉10x10尺寸以下的人脸（仅猜测）

疑问：

1. 其余几乎没有改动，不知道还有没有一些其他的tricks? 
2. 是否考虑过加入bn层训练？之前用pytroch做过复现训练测试，加入bn层后训练更快并且精度更高一点，速度上的变慢和层数的增加可以用bn融合弥补。

期待您的回答！谢谢

**Comment by ShiqiYu** [comment]
最大的变化是输入层去掉了mean，直接uint8输入。

你的bn是怎么增加的？我增加bn未见精度提升。

**Comment by Linzaer** [comment]
@ShiqiYu ，感谢回复~我是在主干的conv后以及第一个分支中的conv后面加了bn，后面三个分支里的conv没有加，widerface上test测试集有1~2个点左右的提升，有一定提升，提升倒不是很大，同时输入均值改为了三通道各减127.5，并且除以128。

**Comment by ShiqiYu** [comment]
我怀疑“三通道各减127.5，并且除以128”作用更大。

**Comment by Linzaer** [comment]
@ShiqiYu 嗯，有可能，我有空单独消融测试下~
