### ISSUE TITLE
How to train person detection model based on this network

### ISSUE THREAD

**Issue by RamatovInomjon** [ShiqiYu/libfacedetection#183]
Hi , thanks for your great job! Your contribution inspired us! 
is it possible person detection model based on this network?
I tried, however result is not good,
how to fine tune existing network for person detection?
Appreciate any suggestions, 
thanks again

**Comment by ShiqiYu** [comment]
I don't think it can work well on person detection. human bodies are more complex than faces. That means you need a relatively complex/bigger model for person detection. Besides, the model can only work well for objects close to squre shape. @RamatovInomjon
