### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by adlerschilling** [ShiqiYu/libfacedetection#184]
Hi!!!

I doing compile for raspbarry pi with command:

cmake \
    -DENABLE_AVX2=ON \
    -DCMAKE_BUILD_TYPE=RELEASE \
    -DDEMO=ON \
     ..

make
 
But when run with command:  ./fdt_demo ../images/keliamoniz2.jpg
return error **Illegal instruction** in line pResults = facedetect_cnn(pBuffer, (unsigned char*)(image.ptr(0)), image.cols, image.rows, (int)image.step); 

You can help me?

**Comment by JiaoPaner** [comment]
check your cpu whether support  AVX2

**Comment by adlerschilling** [comment]
Sorry my delay for reply!

I use Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz and no have support for AVX2, only for AVX.

Thanks for your help, I going remake and testing.
