### ISSUE TITLE
Too many false positive

### ISSUE THREAD

**Issue by JamesHowlettLA** [ShiqiYu/libfacedetection#185]
Many false positive if confidence=97,  
many false negative if   confidence=99,
both false positive and false negative if confidence = 98.

I use fdt_demo to test.

**Comment by SunnyFog** [comment]
![result_cnn_screenshot_04 12 2019](https://user-
images.githubusercontent.com/58533847/70194838-b4b86b80-16b8-11ea-8aaf-b736e88202eb.png)

It detected the primary face reasonably well, but there are a lot of false positives here.

Image 960 x 540
17 faces detected.
face_rect=[  91x  91 @( 639, 166)], confidence=99, angle=0
face_rect=[  19x  19 @( 354, 500)], confidence=89, angle=0
face_rect=[  23x  23 @( 416, 500)], confidence=87, angle=0
face_rect=[  23x  23 @( 880, 500)], confidence=87, angle=0
face_rect=[  25x  25 @( 557, 497)], confidence=86, angle=0
face_rect=[  29x  29 @( 557, 479)], confidence=63, angle=0
face_rect=[  23x  23 @( 579, 501)], confidence=30, angle=0
face_rect=[  23x  23 @( 899, 501)], confidence=30, angle=0
face_rect=[  21x  21 @( 607, 160)], confidence=29, angle=0
face_rect=[  23x  23 @( 940, 496)], confidence=26, angle=0
face_rect=[   9x   9 @(   0, 506)], confidence=25, angle=0
face_rect=[  17x  17 @( 132,  28)], confidence=25, angle=0
face_rect=[  22x  22 @( 922, 500)], confidence=25, angle=0
face_rect=[  24x  24 @( 840,  16)], confidence=25, angle=0
face_rect=[  24x  24 @(  96, 499)], confidence=25, angle=0
face_rect=[  27x  27 @( 805, 496)], confidence=25, angle=0
face_rect=[  26x  26 @( 791, 497)], confidence=25, angle=0

**Comment by ShiqiYu** [comment]
You can remove the results with lower confidence. I just want users can
choose a appropriate threshold according to different applications.
