### ISSUE TITLE
新版本的环境配置问题

### ISSUE THREAD

**Issue by moyimchung** [ShiqiYu/libfacedetection#186]
新版本程序我在windows64位下，VS2017+OpenCV4.0环境中编译后发现没有gst/gst.h这个库，然后自己配置了GStreamer，运行时也通了。但是最后卡在了  croco-0.6.bil   这个库这里。自己在我的电脑面搜也找不到，网上也没有这个文件。用尽所有办法都没法继续下去。
错误提示是：LINK2019 无法提取源文件“croco-0.6.bil”
有人能救救孩子吗

**Comment by ShiqiYu** [comment]
你没必要用gstreamer，你把src目录中的四个文件加入到你的项目一起编译则可。然后按照例子调用函数进行人脸检测。
