### ISSUE TITLE
priorbox是如下Attributes

### ISSUE THREAD

**Issue by luckhhn** [ShiqiYu/libfacedetection#187]
老师您好，谢谢您们的出色的工作和开源!
libfecedetection其中一个priorbox是如下Attributes：

conv3_3_norm_mbox_priorbox：
Attributes如下：
min_size ：10.0 , 16.0 , 24.0
clip：false
variance：0.10000000149 , 0.10000000149 , 0.20000000298 , 0.20000000298
step：8
offset：0.5

SSD官方的其中一个priorbox是如下的Attributes：

min_size：162.0
max_size：213.0
aspect_ratio：2 , 3
flip：true
clip：false
variance：0.1 , 0.1 , 0.2 , 0.2
img_size：300
step：64
offset：0.5

有三个问题像问老师：

1，请问老师，您这min_size 有多个但是max_size却没有，这里很迷惑，麻烦老师帮忙解答一下，我猜测是这样，min_size 为10.0 , 16.0 , 24.0，给定了一个系数，隐形的给了最大值和最小值，在这最大最小值之间取值就是10.0 , 16.0 , 24.0。是这样吗？
2.请问老师，aspect_ratio，这里没有像SSD那样明确的指出来，aspect_ratio是用于得知几个宽高比的，也就是得到每个priorbbox的每个像素值会生成几个defaultbox，比如第一层38*38*K，请问老师这要如何得知其K值？因为从老师的配置文件并没有得知。
3.请问老师，这里没有用flip这个参数的设置，是默认为false吗？

谢谢老师回复，期待

**Comment by ShiqiYu** [comment]
On Thu, Oct 17, 2019 at 9:01 PM luckhhn <notifications@github.com> wrote:

> 老师您好，谢谢您们的出色的工作和开源!
> libfecedetection其中一个priorbox是如下Attributes：
>
> conv3_3_norm_mbox_priorbox：
> Attributes如下：
> min_size ：10.0 , 16.0 , 24.0
> clip：false
> variance：0.10000000149 , 0.10000000149 , 0.20000000298 , 0.20000000298
> step：8
> offset：0.5
>
> SSD官方的其中一个priorbox是如下的Attributes：
>
> min_size：162.0
> max_size：213.0
> aspect_ratio：2 , 3
> flip：true
> clip：false
> variance：0.1 , 0.1 , 0.2 , 0.2
> img_size：300
> step：64
> offset：0.5
>
> 有三个问题像问老师：
>
> 1，请问老师，您这min_size 有多个但是max_size却没有，这里很迷惑，麻烦老师帮忙解答一下，我猜测是这样，min_size 为10.0
> , 16.0 , 24.0，给定了一个系数，隐形的给了最大值和最小值，在这最大最小值之间取值就是10.0 , 16.0 , 24.0。是这样吗？
>
仅仅使用10x10, 16x16, 24x24三个大小的box

>
> 2.请问老师，aspect_ratio，这里没有像SSD那样明确的指出来，aspect_ratio是用于得知几个宽高比的，也就是得到每个priorbbox的每个像素值会生成几个defaultbox，比如第一层38
> *38*K，请问老师这要如何得知其K值？因为从老师的配置文件并没有得知。
>
默认=1，只有一个比例。人脸目标没必要多种比例。

> 3.请问老师，这里没有用flip这个参数的设置，是默认为false吗？
>
这个不记得了

**Comment by luckhhn** [comment]
谢谢老师及时回复。

1.老师说的10x10, 16x16, 24x24，是实验的出来的吗？那为啥要取这些值？还是说有公司推导？

**Comment by ShiqiYu** [comment]
是的，凭感觉吧。
