### ISSUE TITLE
src/facedetectcnn.h: error: must #include <typeinfo> before using typeid

### ISSUE THREAD

**Issue by goodhope258** [ShiqiYu/libfacedetection#189]
src/facedetectcnn.h:200:31: error: must #include <typeinfo> before using typeid
         if (typeid(signed char) != typeid(T))
                               ^
src/facedetectcnn.h:200:44: error: must #include <typeinfo> before using typeid
         if (typeid(signed char) != typeid(T))
                                            ^
src/facedetectcnn.h:233:33: error: must #include <typeinfo> before using typeid
         if (typeid(unsigned char) != typeid(T))
                                 ^
src/facedetectcnn.h:233:46: error: must #include <typeinfo> before using typeid
         if (typeid(unsigned char) != typeid(T))
                                              ^

**Comment by AndyShaw2048** [comment]
#198 You could try it.
