### ISSUE TITLE
Something about "Packing packing = NHWC" in annotated_data_layer of nvidia/caffe

### ISSUE THREAD

**Issue by chenpengf0223** [ShiqiYu/libfacedetection#190]
Hi,
Thanks for your great work.
I try to train the face detection model using nvidia-caffe(https://github.com/NVIDIA/caffe). 
But I met some errors as following:
![image](https://user-images.githubusercontent.com/20535427/68944083-f3f54a00-07e7-11ea-83a4-53a9ddae9733.png)

It seems that annotated_data_layer.cpp，line182: Packing packing = NHWC;
should be changed to ：
Packing packing = NCHW.
Could you please give me some guidance?
Thanks again.

**Comment by ShiqiYu** [comment]
I have no idea about that. Now I moved to pytorch.
