### ISSUE TITLE
训练速度

### ISSUE THREAD

**Issue by xdg2016** [ShiqiYu/libfacedetection#193]
于老师您好，我在使用您的caffe版本训练时，batch_size设置为16，显卡GTX 1060，但是训练起来显存几乎不怎么占用，感觉都用不到gpu的加速，和纯cpu速度差不多，请问有没有什么好的解决办法呢？

**Comment by ShiqiYu** [comment]
模型太小导致，本来计算量小，所以GPU发挥不出威力
