### ISSUE TITLE
Detect facial features

### ISSUE THREAD

**Issue by harshithdwivedi** [ShiqiYu/libfacedetection#196]
Is there a way to detect facial features in an image?

The images in images folder show that it can be done, but I can't find any documentation for doing so.

![](https://raw.githubusercontent.com/ShiqiYu/libfacedetection/master/images/chloecalmon.png)

**Comment by harshithdwivedi** [comment]
@ShiqiYu any pointers on this? Thanks :)

**Comment by ShiqiYu** [comment]
the old binary verison supports landmarker detection, but not avaiable in current CNN version. I may update a version with 5-point landmarkers. But no schedule.

**Comment by harshithdwivedi** [comment]
Ok, thanks!
It would be great if you could update the library when convenient.

Thanks!

**Comment by ShiqiYu** [comment]
The current source code can provide 5 landmark detection.
