### ISSUE TITLE
编译不过去，为什么，请老师指点一下，谢谢

### ISSUE THREAD

**Issue by lyfpeter** [ShiqiYu/libfacedetection#198]
系统环境：
        centos7
执行步骤：
        mkdir build; cd build; rm -rf *
        cmake ..
        make
报错：
`error: must #include <typeinfo> before using typeid   if (typeid(signed char) != typeid(T))`

**Comment by ShiqiYu** [comment]
在头文件添加  #include <typeinfo> 试试
