### ISSUE TITLE
关于树莓派3b+系统的问题

### ISSUE THREAD

**Issue by AndyShaw2048** [ShiqiYu/libfacedetection#200]
老师您好，我研究了几天也没有研究出来，树莓派上应该如何成功运行。

我想请问下老师使用的3b+，安装的系统是什么呢？ubuntu？还是官方系统呢？

各位大佬如果看到这个问题，也请帮我一下，感谢各位。

**Comment by ShiqiYu** [comment]
下载代码，跟你的项目编译在一起则可。
