### ISSUE TITLE
Convert to MNN?

### ISSUE THREAD

**Issue by XP-CHRC** [ShiqiYu/libfacedetection#201]
于老师您好，
我将您models文件夹下的v1模型转换成model.mnn, 输出是一个1200维的向量，我粗略的看了下向量中值，不像是正确的样子(有很多0,分布也不是很规律，没找到对应关系)，请问输出1200维度对么？

**Comment by HapplyPlay** [comment]
老师，您好，为什么新版本检测不出68个特征点了？谢谢！

**Comment by ShiqiYu** [comment]
因为没有关键点功能，很快将发布一个5个特征点的版本。
