### ISSUE TITLE
单人脸照片中检测出多个人脸

### ISSUE THREAD

**Issue by alexdong2002** [ShiqiYu/libfacedetection#203]
测试人脸数据见附件
![example](https://user-images.githubusercontent.com/37401463/71649903-79f43280-2d4d-11ea-80d6-a21586087663.jpg)

当前版本（2019-9月）检测结果见附件
![currentversion-detect](https://user-images.githubusercontent.com/37401463/71650087-bc6a3f00-2d4e-11ea-8959-35f3582e9fd6.png)

之前的版本（2019-3月）结果见附件
![previous-detect](https://user-images.githubusercontent.com/37401463/71650103-d146d280-2d4e-11ea-8351-da947348d2a3.png)

**Comment by ShiqiYu** [comment]
试试刚发布的新版本
