### ISSUE TITLE
Does anybody meet wrong face recognition issue? 

### ISSUE THREAD

**Issue by JeffreyLewis-cd** [ShiqiYu/libfacedetection#204]
Such as hairs, hands or something else were marked as faces.  Demo picture in the bottom of this link page.  https://www.jianshu.com/p/5dc844002d72

**Comment by santo4ul** [comment]
Hi, Yes, I'm facing the same problem with the default configuration. 

There are false positives!

I'm yet to explore the code base. Any idea of how we could improve this? Are there any configuration parameters to play with?

**Comment by JeffreyLewis-cd** [comment]
> Hi, Yes, I'm facing the same problem with the default configuration.
> 
> There are false positives!
> 
> I'm yet to explore the code base. Any idea of how we could improve this? Are there any configuration parameters to play with?

We can use paramter 'confidence' in 'int confidence = p[4]' to identify the real human face. Such as if(confidence > 95){ xxxxxxx}
