### ISSUE TITLE
Create a release on Github

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [ShiqiYu/libfacedetection#205]
Hi! Thank you for the awesome library.
I am interested in packaing this library in Conan (dependency manager for C++), but canot do it without any release version of your library.

Can you make a release, please?

Thank you a lot!

**Comment by ShiqiYu** [comment]
hi, @ZaMaZaN4iK thank you for interesting with the library. How about to download it and use the date of downloading as the release version? 

I'm training an improve version with 5 face landmarks. The current result is encouraging. Hope I will release the new version in 2 weeks.

**Comment by smokris** [comment]
@ZaMaZaN4iK, in the Conan package I created for libfacedetection, it performs a `git checkout` of a specific revision — see https://github.com/vuo/conan-libfacedetection/blob/master/conanfile.py

**Comment by ShiqiYu** [comment]
@ZaMaZaN4iK @Solan8 I just release new source code for better performance and facial landmark detection.
