### ISSUE TITLE
A question about speed acceleration

### ISSUE THREAD

**Issue by RichardSunny1997** [ShiqiYu/libfacedetection#206]
First of all, thank you for this open face-detection library so that my project can be in reality. It is based on YUV images to deal with some things. But I want to speed it up further. And now I have done some works, including using single channel and lifting AVX2 running efficency in the first convolution layer, and the runtime of codes has been decreased by about 4%~5% on my Linux computer. And I'm writing this issue to ask if there are other methods to speed it up. Thanks!

**Comment by ShiqiYu** [comment]
If I know, I will implement in the source code.
