### ISSUE TITLE
请问老师有在WiderFace val测试过指标吗

### ISSUE THREAD

**Issue by DuckJ** [ShiqiYu/libfacedetection#208]

**Comment by ShiqiYu** [comment]
We will do it soon.

**Comment by DuckJ** [comment]
我尝试测了一下train repo里面的模型，origin size下 
Easy      |    Medium  |  Hard
0.835    |    0.806       |   0.626
老师可以参考验证下

**Comment by ShiqiYu** [comment]
@DuckJ Thank you very much!
