### ISSUE TITLE
能调整人脸大小吗？

### ISSUE THREAD

**Issue by KangLin** [ShiqiYu/libfacedetection#209]
程序默认人脸大小为10，如何调整为其它尺寸？

**Comment by ShiqiYu** [comment]
可以缩小图像大小，相当于将最小人脸变大。

**Comment by DuckJ** [comment]
@ShiqiYu 远距离大分辨率，人脸较小情况下，关于网络的设计和数据处理能老师给点建议么?
我考虑的是在随机crop之后的resize尺寸变小点，这样其实网络训练过程的人脸更小了，推理时候自然也可以检测更小人脸了，这样对么
