### ISSUE TITLE
如何将代码封装成库

### ISSUE THREAD

**Issue by Hardold** [ShiqiYu/libfacedetection#21]
您好，我想把代码编译成库供他人使用，我的源代码中有二十个类，分别声明和定义在不同的20个头文件和源文件中，我要如何做才能将代码做成类似您的样子，只提供一个头文件和一个库文件，他人就能使用呢？谢谢您的指导。

**Comment by ShiqiYu** [comment]
https://msdn.microsoft.com/zh-cn/library/ms235636.aspx
