### ISSUE TITLE
How to convert to caffe model

### ISSUE THREAD

**Issue by hejinIzhanghao** [ShiqiYu/libfacedetection#212]
@ShiqiYu
How did you convert the pytroch model to caffe's?

what tools did you use?

**Comment by ShiqiYu** [comment]
I didn't convert the model from pytorch to caffe.

**Comment by hejinIzhanghao** [comment]
the models in libfacedetection/models/caffe/ were trained by caffe, not converted from pytorch ?

**Comment by ShiqiYu** [comment]
Those are old models, not the recent V3 one.
