### ISSUE TITLE
Is this project must be compiled as some special platform?

### ISSUE THREAD

**Issue by xiakj** [ShiqiYu/libfacedetection#213]
when compile the project at vs2015 x64 platform ,this is wrong:
![image](https://user-images.githubusercontent.com/15704302/76154958-3688bc80-6120-11ea-8d6f-d04160a9aef7.png)

`#elif defined(_ENABLE_AVX2)
    {
        int maxarray_int32x8[8];
        _mm256_store_si256((__m256i*)maxarray_int32x8, max_int32x8);
        for (int i = 0; i < 8; i++)
            nMaxValue = MAX(maxarray_int32x8[i], nMaxValue);
    }
#endif`
 
so, how to debug this problem?

**Comment by ShiqiYu** [comment]
Please make sure your CPU can support AVX2. If your CPU supports, maybe it's the problem from VS2015 since it's old. You can update to the newest VS2019. VS2019 is free of charge.

**Comment by zyxrrr** [comment]
I meet same problem,vs2015 x64 can't run, and my CPU supports AVX2, maybe VS2019 is ok.

**Comment by xiakj** [comment]
@ShiqiYu @zyxrrr Yes, it can be compiled correctly in vs2017. And what my question is whether and how I compile this project in vs2015?

**Comment by ShiqiYu** [comment]
@xiakj you can disable AVX2  in file facedetectcnn.h, than you can compile in vs2015.

**Comment by xiakj** [comment]
@ShiqiYu ok. thank you very much!
