### ISSUE TITLE
face detection with thermal images?

### ISSUE THREAD

**Issue by Thanh-Binh** [ShiqiYu/libfacedetection#214]
Do you have any activity for using your algorithm for detecting face on thermal images?
It is very interesting now especially by Corona, where automatical facial temperature detection

**Comment by ShiqiYu** [comment]
If have data, I can develop.

**Comment by Thanh-Binh** [comment]
we have many database for thermal images with facial landmarks from Hongkong University or Aachen Uni.

**Comment by ShiqiYu** [comment]
If the database can be provided, I can train a new model and release it here.

**Comment by Thanh-Binh** [comment]
You can register and Download them http://www4.comp.polyu.edu.hk/~biometrics/polyudb_face.htm

**Comment by Thanh-Binh** [comment]
Or Contact Dr Kopaczka
https://github.com/marcinkopaczka/thermalfaceproject
As far as I know it is available for non-commercial purposes

**Comment by Thanh-Binh** [comment]
For using CNN, I wonder why do you not use tinyDNN, c++ header-only powerful open source for DNN. It allows you to use all wellknown CNN models for learning and inference. Easy to use

**Comment by ShiqiYu** [comment]
> You can register and Download them http://www4.comp.polyu.edu.hk/~biometrics/polyudb_face.htm

It's NIR images, not thermal ones. They are different.

**Comment by ShiqiYu** [comment]
> Or Contact Dr Kopaczka
> https://github.com/marcinkopaczka/thermalfaceproject
> As far as I know it is available for non-commercial purposes

Thermal face images and the image quality is quite good. The faces are also in high resolution. So the images are different with the ones in the virus preventing.

**Comment by Thanh-Binh** [comment]
No different! It is only in different color display!

**Comment by Thanh-Binh** [comment]
Any News from your experiments with FIR images?

**Comment by ShiqiYu** [comment]
I didn't do that because I'm busy on online teaching. You can do that since
I released the training source code.
