### ISSUE TITLE
speed up face detection by omitting land mark detection at inference time

### ISSUE THREAD

**Issue by Fpooyan** [ShiqiYu/libfacedetection#215]
Hi there, thanks for releasing such a great face detection repo. I am using this model on Raspberry 4 and I was wondering if I could speed up face detection by omitting landmark generation at inference time. would you give me any clue if it may help with the acceleration?

**Comment by ShiqiYu** [comment]
Maybe it can improve 0.x% without face landmark detection. 

Make sure to enable -O3 and NEON when you compile the source code.
