### ISSUE TITLE
Build command failed.

### ISSUE THREAD

**Issue by 1109449054** [ShiqiYu/libfacedetection#223]
Build command failed.
Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build F:\FaceDetection\libfacedetection-masterOld\mobile\Android\app\.externalNativeBuild\cmake\debug\arm64-v8a --target facedetection_shared}

ninja: error: 'F:/FaceDetection/libfacedetection-masterOld/mobile/Android/app/src/main/jniLibs/arm64-v8a/libopencv_java4.so', needed by 'F:/FaceDetection/libfacedetection-masterOld/mobile/Android/app/build/intermediates/cmake/debug/obj/arm64-v8a/libfacedetection.so', missing and no known rule to make it

**Comment by 1109449054** [comment]
thanks,my problem was solved

**Comment by howieraem** [comment]
> thanks,my problem was solved

Hi, I'm new to Android, how did you solve this problem?
