### ISSUE TITLE
mac下怎么使用?

### ISSUE THREAD

**Issue by quanjin9099** [ShiqiYu/libfacedetection#227]
按照流程,mac 下编译成功:
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/skaly/Work/code/face/libfacedetection/build/build
Scanning dependencies of target facedetection
[ 25%] Building CXX object CMakeFiles/facedetection.dir/src/facedetectcnn-int8data.cpp.o
[ 50%] Building CXX object CMakeFiles/facedetection.dir/src/facedetectcnn-model.cpp.o
[ 75%] Building CXX object CMakeFiles/facedetection.dir/src/facedetectcnn.cpp.o
[100%] Linking CXX static library libfacedetection.a
[100%] Built target facedetection

并且产生如下文件:
CMakeCache.txt
CMakeFiles
Makefile
 cmake_install.cmake
facedetectionConfig.cmake
facedetection_export.h
 libfacedetection.a
libfacedetectionConfigVersion.cmake

我应该怎么使用呢?

**Comment by ShiqiYu** [comment]
link libfacedetection.a as a static lib with your program.
