### ISSUE TITLE
人脸检测结果循环时pBuffer的offset为啥是142

### ISSUE THREAD

**Issue by FanglaiPeng** [ShiqiYu/libfacedetection#237]
在facedetectcnn-model.cpp LINE 421:
short * p = ((short*)(result_buffer + 4)) + 142 * size_t(i);
请问这里为什么是142，怎么算出来的。

**Comment by ShiqiYu** [comment]
defined by an old version years ago. We keep the API unchanged.

**Comment by 375000384** [comment]
余老师你好，  facedetect_multiview_reinforce(pBuffer，....)，这里的 pBuffer使用后需要手工 free(pBuffer) 吗？  程序一直在 free(pBuffer)这个位置过不去，以前是正常的，现在不知道怎么就突然不行了。
_ASSERTE(_CrtIsValidHeapPointer(pBuffer))  这个验证失败。
请指教。
![free(pBuffer) bug](https://user-images.githubusercontent.com/53556908/78310987-2aa6e380-7582-11ea-8b8b-6f0037b33c80.png)

**Comment by zhongmingen** [comment]
//此模型的一个人脸的信息包含142个short类型的数据
//早期版本中，0-3对应人脸矩形框的(x,y,w,h)，4对应neighbors ，5对应angle ，6-141对应68个landmark，共计142个short
//后期版本中，0为可信度、1-4对应人脸矩形框的(x,y,w,h)，5-14对应5个landmark，最后剩下的空间没有用
