### ISSUE TITLE
想请问一下余老师多线程的程序是怎么处理动态分配的内存的，动态分配内存在多个线程内同时调用如何避免竞争的情况

### ISSUE THREAD

**Issue by jasonlst** [ShiqiYu/libfacedetection#245]

**Comment by lsmilesmile** [comment]
兄弟解决了没？我也是要多线程调用，总是内存访问出错。。

**Comment by jasonlst** [comment]
解决了，参照余老师给出的benchmark写就行，一定要记得像benchmark一样在主线程中引用一次facedetect_cnn函数否则内存访问就会出错，但是我跑出来的多线程数据和余老师的数据有着很大的偏差，不知道是什么原因

**Comment by ShiqiYu** [comment]
> 解决了，参照余老师给出的benchmark写就行，一定要记得像benchmark一样在主线程中引用一次facedetect_cnn函数否则内存访问就会出错，但是我跑出来的多线程数据和余老师的数据有着很大的偏差，不知道是什么原因

函数第一次被调用时会初始化一些参数，初始化不支持并行，所以多线程调用之前需要先单独调用一下进行初始化。
