### ISSUE TITLE
Examples dont work

### ISSUE THREAD

**Issue by Allius27** [ShiqiYu/libfacedetection#254]
Good day.

I build your project and examples with opencv 4.3.0, but it doesn't work

Steps: 
1) build opencv
2) git clone https://github.com/ShiqiYu/libfacedetection
3) cd libfacedetection
4) mkdir build && cd build
5) cmake  -DDEMO=ON -DOpenCV_DIR=/home/i123/install/lib/cmake/opencv4 .. && make
6) ./detect-camera-demo 0

And as result I got this :"Illegal instruction (core dumped)"

Might your library work under Ubuntu?

**Comment by Allius27** [comment]
Or  is that incompatible with latest opencv?

**Comment by ShiqiYu** [comment]
maybe you enabled AVX2 or AVX512 that your CPU doesn't support.

**Comment by Allius27** [comment]
True, examples work with turned off AVX2 and AVX512 options(intel core i7) 

Thank you for advice

**Comment by ShiqiYu** [comment]
You can enable AVX2 and disable AVX512 to gain better speed

**Comment by Allius27** [comment]
I tryed build project with different options, and for it works only with turned off options

**Comment by ShiqiYu** [comment]
It's strange. i7 CPU should support AVX2.
