### ISSUE TITLE
海思 Hi3556av100编译出错

### ISSUE THREAD

**Issue by qq297110281** [ShiqiYu/libfacedetection#261]
很好的项目，最近在尝试移植到hi3556av100 这个平台上是编译一直报：
/opt/hisi-linux/x86-arm/arm-himix200-linux/lib/gcc/arm-linux-gnueabi/6.3.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"
 #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"

尝试按照提示修改mfloat-abi=softp or -mfloat-abi=hard 都不行。请问有什么建议么？

**Comment by qq297110281** [comment]
解决了，对于hi3556av100.编译选项应该加上：
add_definitions(-mcpu=cortex-a53 -mfloat-abi=softfp -mfpu=neon-vfpv4 -mfp16-format=ieee)
即：
![image](https://user-images.githubusercontent.com/8348315/84358586-f0009d80-abf9-11ea-91cf-03c145b5a2eb.png)

**Comment by H0RlZ0N** [comment]
请问该开源库在hi3556av100上的检测效率和准确度如何？我试着移植到hi3516a上发现检测人脸效率和准确度均达不到预期
