### ISSUE TITLE
no 68 landmark detection?

### ISSUE THREAD

**Issue by SE2AI** [ShiqiYu/libfacedetection#264]
the changelog says:
```
2017-01-20:
* 68-point landmark detection added.
```
but can not find any code or models related to 68 landmarks？
did I miss something?

**Comment by fengyuentau** [comment]
It was the old model which is not deep learning-based. You can find it by looking back to the old commits. We are planning to release a deep learning-based model with the 68-landmark detection. Please stay tune.
