### ISSUE TITLE
facedetection_export.h No such file or directory

### ISSUE THREAD

**Issue by naushadck** [ShiqiYu/libfacedetection#278]
Helllo, 

Following error while compile the code. 

facedetection_export.h no such file or directory

How to resolve it....

**Comment by vungoc98** [comment]
you can find at issue #222

**Comment by fengyuentau** [comment]
Refer to the section from `README.md`:
> Please add facedetection_export.h file in the position where you copy your facedetectcnn.h files, add #define FACEDETECTION_EXPORT to facedetection_export.h file. See: issues #222
