### ISSUE TITLE
undefined reference to `facedetect_cnn(unsigned char*, unsigned char*, int, int, int)'

### ISSUE THREAD

**Issue by patelajaychh** [ShiqiYu/libfacedetection#285]
```bash
/tmp/ccHJpJrK.o: In function `main':
detect_face.cpp:(.text+0x1d4): undefined reference to `facedetect_cnn(unsigned char*, unsigned char*, int, int, int)'
collect2: error: ld returned 1 exit status
```

Please review this ....

**Comment by fengyuentau** [comment]
Please follow our [guide](https://github.com/ShiqiYu/libfacedetection/blob/master/COMPILE.md) to compile.
If you still have problems, please provide more details on which OS you use and how you compile.

**Comment by aa92478** [comment]
I have same problem. I compile in Raspberry pi. and then cmake can find facedetection find_package(facedetection) is work. but it still has this error. 
cmake \
	-D CMAKE_BUILD_TYPE=Release \
	-D ENABLE_AVX2=OFF \
	-D ENABLE_AVX512=OFF \
	-D ENABLE_NEON=ON \
	-D USE_OPENMP=ON \
	-D DEMO=OFF \
	-D CMAKE_CXX_FLAGS=-mfpu=neon \
	..

**Comment by fengyuentau** [comment]
I have a Raspberry PI incoming in the next few days, will check this out for you guys.

**Comment by fengyuentau** [comment]
> I have same problem. I compile in Raspberry pi. and then cmake can find facedetection find_package(facedetection) is work. but it still has this error.
> cmake
> -D CMAKE_BUILD_TYPE=Release
> -D ENABLE_AVX2=OFF
> -D ENABLE_AVX512=OFF
> -D ENABLE_NEON=ON
> -D USE_OPENMP=ON
> -D DEMO=OFF
> -D CMAKE_CXX_FLAGS=-mfpu=neon
> ..

@aa92478 I failed to build the project with option `-D CMAKE_CXX_FLAGS=-mfpu=neon`. Tried to build without this option and it worked. Feel free to leave comments if you still have problems regarding compiling.
