### ISSUE TITLE
Julia Wrapper

### ISSUE THREAD

**Issue by SimonDanisch** [ShiqiYu/libfacedetection#286]
Hi, 

Not sure if this is interesting for you, but I made a Julia wrapper for this package:

https://github.com/SimonDanisch/LibFaceDetection.jl
It works natively on all platforms supported by Julia, and the cross compiled binaries can be used by everyone:
https://github.com/JuliaBinaryWrappers/libfacedetection_jll.jl/releases/tag/libfacedetection-v3.0.0%2B0
We'll soon add binaries for avx2 etc as well.

Best,
Simon

**Comment by ShiqiYu** [comment]
Happy to see that!
