### ISSUE TITLE
还是喜欢前几年非cnn的人脸检测版本，还能找到吗，都没有tag···

### ISSUE THREAD

**Issue by apple1987** [ShiqiYu/libfacedetection#288]
还是喜欢前几年非cnn的人脸检测版本，还能找到吗，都没有tag···cnn这个cpu下比之前的慢~~~~
所有于老师可以再提供之前版本的下载链接吗

**Comment by fengyuentau** [comment]
@apple1987 您可以根据changlog追溯找到非cnn版本的commit id。

**Comment by zaidao2023** [comment]
你好 问一下 你找到之前的非cnn算法了吗
