### ISSUE TITLE
build warning in facedetectcnn.h:395:20

### ISSUE THREAD

**Issue by rockcarry** [ShiqiYu/libfacedetection#292]
when compiling I get build warning:

facedetectcnn.h:395:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (int i = 0; i < filters.size(); i++)
                  ~~^~~~~~~~~~~~~~~~

**Comment by fengyuentau** [comment]
Could you provide more information about your environment, such as compiler and compiling command?

**Comment by rockcarry** [comment]
my enviroment is ubuntu 14.04

https://github.com/rockcarry/libfacedetection-test

this is the test code.

**Comment by fengyuentau** [comment]
You can try replace `int` with `size_t`.
