### ISSUE TITLE
有没有可以和这个工程配合的身份识别方案

### ISSUE THREAD

**Issue by Kingstom8MB** [ShiqiYu/libfacedetection#295]
我使用PyFaceDet（这个工程的Python版本）可以检测到足够小的人脸（18X18）。请问有没有哪个项目可以在这么小的人脸上进行身份识别呢？我目前有使用到这么小的人脸识别需求，但是没有还没有找到可行的方案，来请教一下

**Comment by fengyuentau** [comment]
我们目前仅做人脸检测。
