### ISSUE TITLE
关于量化的问题

### ISSUE THREAD

**Issue by ddxoxpp** [ShiqiYu/libfacedetection#296]
老师你好，请问能分享一下代码中前向推导里量化数据以及其scale，bias计算的理论基础吗，感觉代码跟我自己所了解的量化有一些小区别，但不知道为什么会这样计算

**Comment by fengyuentau** [comment]
量化的代码实现在https://github.com/ShiqiYu/libfacedetection.train/blob/51366d267a5997371506b6080df8719f58e20852/tasks/task1/yufacedetectnet.py#L162-L194

**Comment by andguilty** [comment]
> 量化的代码实现在https://github.com/ShiqiYu/libfacedetection.train/blob/51366d267a5997371506b6080df8719f58e20852/tasks/task1/yufacedetectnet.py#L162-L194

谢谢，我想问的是量化传递的问题，就是卷积后的中间结果及其scale和bias（话说特征图怎么会有bias）为什么是像facedetectcnn.cpp代码里那样计算的？

**Comment by fengyuentau** [comment]
我们用的是对称的8bit量化，你可以看看这里https://zhuanlan.zhihu.com/p/164901397

**Comment by andguilty** [comment]
> 我们用的是对称的8bit量化，你可以看看这里https://zhuanlan.zhihu.com/p/164901397

谢谢分享，我去学习学习

**Comment by andguilty** [comment]
> 我们用的是对称的8bit量化，你可以看看这里https://zhuanlan.zhihu.com/p/164901397

麻烦再问一下，我仍然不明白特征图的bias的含义，为何该bias是由round（scale）得到的，以及特征图int32量化为unsigned int8要加上0.499f的原因。

**Comment by andguilty** [comment]
> > 我们用的是对称的8bit量化，你可以看看这里https://zhuanlan.zhihu.com/p/164901397
> 
> 麻烦再问一下，我仍然不明白特征图的bias的含义，为何该bias是由round（scale）得到的，以及特征图int32量化为unsigned int8要加上0.499f的原因。

我好像理解了特征图bias的含义了，但是0.499还是不明白

**Comment by on-your-way** [comment]
> > > 我们用的是对称的8bit量化，你可以看看这里https://zhuanlan.zhihu.com/p/164901397
> > 
> > 
> > 麻烦再问一下，我仍然不明白特征图的bias的含义，为何该bias是由round（scale）得到的，以及特征图int32量化为unsigned int8要加上0.499f的原因。
> 
> 我好像理解了特征图bias的含义了，但是0.499还是不明白

It means the 'round' function for adding 0.499f. If you don't do that, it means the 'floor' function.
