### ISSUE TITLE
Recommended size for images?

### ISSUE THREAD

**Issue by LostVector** [ShiqiYu/libfacedetection#297]
Hi,

What would be the best resolution to resize a high resolution image to if we want to run libfacedetection on it?  I couldn't find this documented anywhere and it seems to be important to do based on some limited testing.

**Comment by fengyuentau** [comment]
It depends on the sizes of faces. We recommend that one should resize the image accordingly so that the sizes of faces fall into 10x10 ~ 300x300.

**Comment by LostVector** [comment]
Thanks, very helpful.
