### ISSUE TITLE
undefined reference to symbol 'omp_get_num_threads@@OMP_1.0'

### ISSUE THREAD

**Issue by aa92478** [ShiqiYu/libfacedetection#302]
g++ detect-image.cpp -o test `pkg-config --cflags --libs opencv` -I ../src/ -L ../build/ -lfacedetection
/usr/bin/ld: /usr/local/lib/libfacedetection.a(facedetectcnn-model.cpp.o): undefined reference to symbol 'omp_get_num_threads@@OMP_1.0'
/usr/bin/ld: //lib/arm-linux-gnueabihf/libgomp.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by fengyuentau** [comment]
Please use cmake to build the project. And probably you are missing flags or options for linking openmp. Try to add flag `-fopenmp` when compiling and linking.

**Comment by fengyuentau** [comment]
I used `cmake` to build the project on my raspberry pi 4b without problems. Please build the project using `cmake`.
