### ISSUE TITLE
Some questions for v3

### ISSUE THREAD

**Issue by on-your-way** [ShiqiYu/libfacedetection#303]
Thanks for your great work!
As I know, v1 is a non-DL method based on the Multi-Block LBP feature. However, source codes of v1 are missing now. (Will you send me a copy, please? I really want to learn it and my email is taoyusinc@qq.com. Thanks a lot!)
v2 has great improvement by CNN. Nevertheless, its No. parameters is more than 2M (If wrong, please correct me).
v3, which was released on March 29, reduced the No. parameters to 0.12M by less channels and depth-wise separable convolution mainly. Some layers of v2 has 256 channels, while v3 has no more than 64 channels.
So, I want to ask that how you reduce channels.  Looking forward to your reply.

**Comment by fengyuentau** [comment]
If I recall correctly, v1 (non-DL) is not fully open-source, so no source code can be found. As for reducing channels, we ran experiments to validate different channels. We are working on a lighter, faster, and more accurate version than the current one. Stay tune for the release.
