### ISSUE TITLE
你好，有V3量化的版本吗？

### ISSUE THREAD

**Issue by cvtuge** [ShiqiYu/libfacedetection#304]
V3有int8量化的版本吗

**Comment by fengyuentau** [comment]
https://github.com/ShiqiYu/libfacedetection/tree/bf41b77d651d637d294aaeb32bc5a68453571a5e这个是今年过年前的V3版本，是int8量化的。我们现在正在基于V3进一步开发，请留意未来的更新。

**Comment by cvtuge** [comment]
> https://github.com/ShiqiYu/libfacedetection/tree/bf41b77d651d637d294aaeb32bc5a68453571a5e 这个是今年过年前的V3版本，是int8量化的。我们现在正在基于V3进一步开发，请留意未来的更新。

你好，我看这个链接里面的模型权重还是float的？

**Comment by fengyuentau** [comment]
@cvtuge 不好意思，应该是这个网址才对：
https://github.com/ShiqiYu/libfacedetection/tree/89a88443ff1075de3df06dbffb95d8f2c10c44de

**Comment by cvtuge** [comment]
> @cvtuge 不好意思，应该是这个网址才对：
> https://github.com/ShiqiYu/libfacedetection/tree/89a88443ff1075de3df06dbffb95d8f2c10c44de

V3版本的训练代码有吗，libfacedetection.train里面的模型，跟最新的部署代码对应不上？

**Comment by fengyuentau** [comment]
@cvtuge 目前V3模型还在持续优化中，暂时先放出前向推理的版本。等模型稳定之后再更新libfacedetection.train里面的代码和模型。
