### ISSUE TITLE
FLOPs

### ISSUE THREAD

**Issue by nttstar** [ShiqiYu/libfacedetection#306]
Hi, how about the FLOPs of your new v3 CNN model(under 640x480 input)?

**Comment by fengyuentau** [comment]
For CONV layers, we calculate FLOPs as the following:
```
FLOPs_conv = (2 * C_in * K * K - bias) * (C_out // groups) * H_out * W_out
```

So the FLOPs of CONV layers in our 85K-param model is about 0.767 GFLOPs under a 640x480 input.
