### ISSUE TITLE
85K个参数是怎么算出来的？

### ISSUE THREAD

**Issue by wang-kangkang** [ShiqiYu/libfacedetection#307]
3*3*3*32+1*1*32*16 + 3*3*16*32+1*1*32*32 + 3*3*32*64+1*1*64*32+3*3*32*64+3*3*64*128=119648，加到model4的第一个卷积就已经超了

**Comment by fengyuentau** [comment]
如果您参考的模型代码是[libfacedetection.train](https://github.com/ShiqiYu/libfacedetection.train)，目前这个仓库的代码并不是最新的。我们会尽快更新最新的模型训练代码，还请您关注。

**Comment by wang-kangkang** [comment]
> 如果您参考的模型代码是[libfacedetection.train](https://github.com/ShiqiYu/libfacedetection.train)，目前这个仓库的代码并不是最新的。我们会尽快更新最新的模型训练代码，还请您关注。

那本代码库（libfacedetection）是最新的吗？我看模型似乎和libfacedetection.train一样？

**Comment by wang-kangkang** [comment]
> 本代码库是最新的，但使用的模型并不是目前libfacedetection.train（commit id 0340ddb89a8da629efb9c3f54d2b5eae2c801dd6）中的模型。

能说下是哪个模型吗？我在models/caffe下找了两个模型算了下，都不是85K

**Comment by fengyuentau** [comment]
目前只有权重文件https://github.com/ShiqiYu/libfacedetection/blob/master/src/facedetectcnn-data.cpp 。models/caffe下面的是老本版（v1/v2）的模型。
