### ISSUE TITLE
demo图片人脸检测rect错误

### ISSUE THREAD

**Issue by wangzheng2019** [ShiqiYu/libfacedetection#308]
我用了ios demo工程的test.jpg，测试了v2 和 v3版本测试，结果都不正确，感觉上好像是我使用方式有问题，求指点…
原图：
![test](https://user-images.githubusercontent.com/56950799/117620753-5d6ad480-b1a3-11eb-968e-df08455e83aa.jpg)
结果：

![res2](https://user-images.githubusercontent.com/56950799/117620865-80958400-b1a3-11eb-9d67-c4548011b35e.jpg)

测试代码：
![{0F98A93A-629B-0ECF-2592-B279169F4CC6}](https://user-images.githubusercontent.com/56950799/117621138-dbc77680-b1a3-11eb-82f2-303b8d5ec716.png)

**Comment by fengyuentau** [comment]
您用的测试代码对应的是老版本的，您应该用[example/detect-image.cpp](https://github.com/ShiqiYu/libfacedetection/blob/master/example/detect-image.cpp)里面的代码去测试。我这边测试没问题。


主要区别是下面几行：
https://github.com/ShiqiYu/libfacedetection/blob/06f5e92fe868d6b13803cec679853bf1e1e0979f/example/detect-image.cpp#L91-L98
也就是p里面的内容不一样了。
