### ISSUE TITLE
facedetectcnn.cpp中convolutionDP函数为什么是先Pointwise卷积再Depthwise卷积？

### ISSUE THREAD

**Issue by liulangxing** [ShiqiYu/libfacedetection#309]
正常的Depthwise Separable Convolution不是应该是先Depthwise卷积再Pointwise卷积么？改为先Pointwise卷积再Depthwise卷积有什么优势或者特殊作用吗？

**Comment by fengyuentau** [comment]
从网络整体来看，其实先pw后dw或者先dw后pw都没关系，网络中间都可以视为先dw后pw。
我们先pw后dw的考虑是，pw先的话可以在特征图进来的时候就调整通道数。

**Comment by liulangxing** [comment]
多谢解惑~
