### ISSUE TITLE
question about training samples

### ISSUE THREAD

**Issue by chibai** [ShiqiYu/libfacedetection#31]
I read your article to know that you have 20GB+ negative samples.
But do you include the hard negative samples?? 
when I said hard negative samples, I mean a patch, that only part of the patch containing only part of the face, like this one.

![1](https://cloud.githubusercontent.com/assets/5702248/23600355/4104b494-0281-11e7-859d-e0c9d608c442.png)

**Comment by ShiqiYu** [comment]
No

**Comment by bluekingdom** [comment]
@chibai Which achicle you mention? Can you give me the title or link, thx~~~
