### ISSUE TITLE
实时视频使用多线程处理

### ISSUE THREAD

**Issue by Wasabi111** [ShiqiYu/libfacedetection#312]
余老师，您好！
之前有个issue提到图片使用多线程处理的问题，您提到由于初始化问题，facedetect需要先调用一次，再使用多线程处理。
但对于实时视频输入，获取帧有严格先后顺序，似乎不像图片那么好处理，您有什么建议吗？谢谢！

**Comment by ShiqiYu** [comment]
你可以随便找个什么图像，先调用一次，进行初始化。

**Comment by Wasabi111** [comment]
谢谢您的答复！对于如何把实时采集的视频帧交付多线程处理，我目前的想法是摄像头获取帧和facedetect分开，每有新的帧就交付一个线程去处理，最后再把所有处理的结果join在一起，您觉得合理吗？谢谢！

**Comment by Wasabi111** [comment]
视频处理当作多张图片然后用openmp或者分给多个线程做都可以，另外也可以把视频分为几段，每一段给一个线程处理
