### ISSUE TITLE
对于图片不同分辨率识别算法的精度问题

### ISSUE THREAD

**Issue by Wasabi111** [ShiqiYu/libfacedetection#326]
Prof. Yu 您好，

我在使用您的库时，发现如果图片或者摄像头是1280*720或者1920*1080的分辨率时，寻找到的人脸特征点帧与帧之间跳动很大。但是在统一先resize到640*480或者更低分辨率时就没有问题。请问这个现象是否正常，谢谢！

祝好，
常东明

**Comment by fengyuentau** [comment]
要检测的人脸的尺寸最好是在300x300到10x10之间，否则对于太大或者太小的人脸，检测的结果会没那么好。
