### ISSUE TITLE
NCNN implementation?

### ISSUE THREAD

**Issue by tsangz189** [ShiqiYu/libfacedetection#334]

**Comment by fengyuentau** [comment]
Do it yourself or Google it.

**Comment by tsangz189** [comment]
So how do you generate the priorbox without using opencv dnn module? I saw other issue mentioned this but the file is no longer accessible
Thanks

**Comment by fengyuentau** [comment]
Please, take a look at the code in opencv https://github.com/opencv/opencv/blob/50707a274156406708752cb3c29d3e32c3b0e1cc/modules/objdetect/src/face_detect.cpp#L116-L176

**Comment by tsangz189** [comment]
many thanks
