### ISSUE TITLE
error: use of undeclared identifier 'facedetect_cnn'

### ISSUE THREAD

**Issue by rajhlinux** [ShiqiYu/libfacedetection#337]
PC info:
OS: FreeBSD 13.1-RELEASE-p1 amd64 
Resolution: 3840x2160 
DE: Plasma 5.24.6 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: dolphin 
CPU: AMD FX-8350 (8) @ 3.991GHz 
GPU: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
Memory: 7781MiB / 32684MiB 

using clang++:
clang++ -v -g /home/user/libfacedetection/example/detect-camera.cpp -o /home/user/libfacedetection/example/detect-camera $(pkg-config --cflags --libs opencv4) -I /usr/local/include/opencv4/

Error:

```
/home/user/libfacedetection/example/detect-camera.cpp:97:24: error: use of undeclared identifier 'facedetect_cnn'
            pResults = facedetect_cnn(pBuffer, (unsigned char*)(image.ptr(0)), image.cols, image.rows, (int)image.step);
```
What could be the issue?

Also will this project work with CPU that have AVX and not AVX2?

Thanks.

**Comment by fengyuentau** [comment]
Please, use CMake to build this project. https://github.com/ShiqiYu/libfacedetection/blob/master/CMakeLists.txt

**Comment by rajhlinux** [comment]
Hello [fengyuentau](https://github.com/fengyuentau), Thanks for your reply. I will try that.

**Comment by fengyuentau** [comment]
> Also when running the "detect-camera-demo", nothing happens:
> ```
> $ ./detect-camera-demo /dev/video4
> ```

I think the parameter should be the number of the webcame on your pc (start from 0). See following lines from `detect-camera.cpp`:

https://github.com/ShiqiYu/libfacedetection/blob/14abaa7b171e18c7450d1778bf22dddf03c53a32/example/detect-camera.cpp#L69-L77

**Comment by rajhlinux** [comment]
Hello [fengyuentau](https://github.com/fengyuentau), thanks for the reply.

Thank You very much, I got it running now, using:
`$ ./detect-camera-demo 4`

![screenshot](https://user-images.githubusercontent.com/61344181/190303681-1fe6d0a9-05df-4347-9556-46e2abc9276b.jpg)

Are there any ways I can implement this code on OpenCL or AMD GPU?
Is there any manual for changing the library?

Thanks.

**Comment by fengyuentau** [comment]
> Are there any ways I can implement this code on OpenCL or AMD GPU?

You need to do this yourself, or try OpenCV which comes with OpenCL support. Simply set the corresponding backend (`cv.dnn.DNN_BACKEND_DEFAULT`) and target (`cv.dnn.DNN_TARGET_OPENCL`):
https://github.com/ShiqiYu/libfacedetection/blob/14abaa7b171e18c7450d1778bf22dddf03c53a32/opencv_dnn/python/detect.py#L38-L46

> Is there any manual for using the library?

There is a section in compile.md on the usage: https://github.com/ShiqiYu/libfacedetection/blob/master/COMPILE.md#usage

**Comment by rajhlinux** [comment]
I installed dlib and now get errors when running the same executable for "detect-camera-demo":

It threw an error about:
`"libopencv_gapi.so.405" not found which is required by detect-camera-demo`

So I deleted everything and recompiled again and now get core dump error:

```
$ ./detect-camera-demo 4

[ WARN:0@0.326] global /wrkdirs/usr/ports/graphics/opencv/work/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
time = 2892.56ms
2 faces detected.
face 0: confidence=84, [184, 451, 30, 36] (190,464) (201,464) (193,471) (191,477) (199,477)
face 1: confidence=29, [454, 411, 136, 136] (523,479) (544,485) (536,503) (519,510) (535,515)
Abort trap (core dumped)
```

Thanks.

**Comment by rajhlinux** [comment]
Alright, I figured out what caused the issue. It seems that I can run the compiled binaries again if I completely remove OpenCV 4.5 which was installed on my PC or compile to the latest version of OpenCV 4.6 which will not conflict when running the compiled binaries.

Thanks.
