### ISSUE TITLE
Any examples on how to do face alignment?

### ISSUE THREAD

**Issue by rajhlinux** [ShiqiYu/libfacedetection#343]
Hello does libfacedetection have any face alignment implementation?

If so are there any examples?

Thanks.

**Comment by fengyuentau** [comment]
This library is for detecting faces. In case of face alignment, you can take a look at the OpenCV source code:

https://github.com/opencv/opencv/blob/23edec83fb0fe2ca5d5938b180a010a3402c19cb/modules/objdetect/src/face_recognize.cpp#L29-L42
