### ISSUE TITLE
Where to find the original model export the current version facedetectcnn-data.cpp

### ISSUE THREAD

**Issue by jb2020-super** [ShiqiYu/libfacedetection#344]
I have try to export the https://github.com/ShiqiYu/libfacedetection.train/blob/master/weights/yunet_final.pth to cpp by using the provided exportcpp.py. But noticed that the exported network structure and parameters is different from facedetectcnn-data.cpp.
Is there anything I missed when running the script? Thanks.

**Comment by fengyuentau** [comment]
cc @Wwupup .

IIRC, the model in this repo is one version in advance of the model in the training repo.

**Comment by Wwupup** [comment]
This version match the current libfacedetection.train repo https://github.com/ShiqiYu/libfacedetection/tree/2d02619c44d1877879f6699ca565c1737c17b3f6,
And the new version of libfacedetection.train repo will comming soon.

**Comment by jb2020-super** [comment]
Thank you for your reply, looking forward to the new version.
