### ISSUE TITLE
关于facedetect_cnn函数定义

### ISSUE THREAD

**Issue by biepenghaomie** [ShiqiYu/libfacedetection#351]
我在facedetectcnn-model.cpp中找到了facedetect_cnn函数的定义，注释写着“input image, it must be RGB (three-channel) image!”而在头文件中facedetectcnn.h写着"input image, it must be BGR (three channels) insteed of RGB image!"。我觉得虽然是个小问题，但不一致的代码注释可能引起阅读混乱？

**Comment by Wwupup** [comment]
@biepenghaomie 你好，确实存在注释不一致的问题。算法的输入应该是直接从OpenCV得到的BGR的图片，混淆的注释会随后更正。
