### ISSUE TITLE
错误	LNK1120	1 个无法解析的外部命令	

### ISSUE THREAD

**Issue by Chigland** [ShiqiYu/libfacedetection#352]
运行后提示如下：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "int * __cdecl facedetect_cnn(unsigned char *,unsigned char *,int,int,int)" (?facedetect_cnn@@YAPEAHPEAE0HHH@Z)，函数 main 中引用了该符号	ConsoleApplication1	D:\C\ConsoleApplication1\ConsoleApplication1\main.obj	1	

在facedetectcnn.h中只有
FACEDETECTION_EXPORT int * facedetect_cnn(unsigned char * result_buffer,  unsigned char * rgb_image_data, int width, int height, int step); 
这一个声明

**Comment by Wwupup** [comment]
你好 @Chigland ，调用时请参考example中的例子。
