### ISSUE TITLE
facedetectcnn-data.cpp里的层和通过libfacedetection.train   yunet_n.py导出的yunet2cpp.py导出的层不一致

### ISSUE THREAD

**Issue by nianfd** [ShiqiYu/libfacedetection#366]
facedetectcnn-data.cpp里的层和通过libfacedetection.train   yunet_n.py yunet2cpp.py导出的层不一致，导致C++工程用不了，多了下面几层：
![image](https://github.com/ShiqiYu/libfacedetection/assets/41506818/eb4c1c1a-f04c-4c46-bdc9-0285b1c24a6d)

**Comment by Wwupup** [comment]
@nianfd 目前的C++库是使用yunet-s.pth导出的而不是使用yunet-n.pth。若想要使用yunet-n.pth，可以自行对facedetect-model.cpp进行修改。
