### ISSUE TITLE
灰度图  vs RGB图输入的问题

### ISSUE THREAD

**Issue by laxusvip** [ShiqiYu/libfacedetection#367]
请问一下为什么不直接用灰度图作为输入呢？因为我们人眼识别其实灰度图就能识别出是不是人脸了、不需要RGB。改成灰度图、3通道改为单通道，是不是可以直接耗时减少到1/3，感觉是很合算的、精度如果低一点也能接受。

**Comment by Wwupup** [comment]
@laxusvip 你好，如果想要使用灰度图作为输入，可以重新训练一个模型接收灰度输入即可。但是3通道到输入改为1通道输入仅仅是降低网络的第一层的计算量，对整个人脸检测流程没有明显的加速。
