### ISSUE TITLE
mingw: ld returned 1 exit status 

### ISSUE THREAD

**Issue by Sundrops** [ShiqiYu/libfacedetection#41]
I compiled the example code  using mingw and got this error:
obj\Release\main.o:main.cpp:(.text.startup+0x20d)||undefined reference to `_imp___Z18facedetect_frontalPhS_iiifiiii'|
I also convert .lib to .a with reimp, but It doesn't work.
What should I do? Thanks a lot!

**Comment by smartadpole** [comment]
我也遇到了同样的问题，mingw编译器，编译报错
error: undefined reference to `_imp___Z18facede
