### ISSUE TITLE
for linux ? 没有Linux下的库

### ISSUE THREAD

**Issue by hicaoc** [ShiqiYu/libfacedetection#42]
有没有计划linux的版本呢？

**Comment by xhbdahai** [comment]
ARM Linux的 .so有。Aarch32和Aarch64。
https://github.com/OAID/YSQfastfd

**Comment by VincentZhuo** [comment]
于老师，您好！我最近在学习您的检测算法，算法确实很高效。想请问一下有没有普通Linux版本的呢？

**Comment by xhbdahai** [comment]
目前是在Arm Linux上的版本。

**Comment by loulansuiye** [comment]
如果能够开源就好了，这样大家可以贡献各自的力量
