### ISSUE TITLE
hi, what's the face detection algorithm this lib using? 

### ISSUE THREAD

**Issue by GoodJoey** [ShiqiYu/libfacedetection#45]

**Comment by alexyangfox** [comment]
Saw this on Dr Yu 's [website](http://yushiqi.cn/research/face-detection): 


> We trained a face detector which can achieve state-of-the-art performance. Some details are as follows:   
>
>    Feature: LBP   
>    Classifier: Gentle AdaBoost   
>    Positives samples: ~150,000

**Comment by dexception** [comment]
@alexyangfox 

I highly doubt it. It looks like some sort of voila jones face detector with some filters and optimizations.
