### ISSUE TITLE
Java JNA 调用失败

### ISSUE THREAD

**Issue by wellpeng** [ShiqiYu/libfacedetection#46]
当使用 JNA 调用时，由于头文件 __declspec(dllexport) 时没有 extern "C" 而导致无法调用 dll 的函数。
当定义了之后，如果没有 #define FACEDETECTDLL_EXPORTS 也会导致无法调用。

**Comment by wellpeng** [comment]
搞定，自己封装了个 dll 来调用于老师的 dll，用查看 dll 依赖的工具（dependency walker）找出了函数签名，然后用 JNI 来调用。不依赖 demo 中的 opencv mat 来灰度化图片，而是 Java 重写了图片灰度化方法来获取字节。有需要的同学可以 email 我。

**Comment by wangwang194** [comment]
你好，我想问一下，在封装的时候出现
   错误	13	error LNK2001: 无法解析的外部符号 "__declspec(dllimport) int * __cdecl facedetect_multiview_reinforce(unsigned char *,unsigned char *,int,int,int,float,int,int,int,int)" (__imp_?facedetect_multiview_reinforce@@YAPAHPAE0HHHMHHHH@Z)	E:\workspace\opencv\2017.11.24\Client\Client\ImageProcess.obj	Client
   这种怎么解决，lib已经添加了，但是不知道是哪个地方出现问题？
