### ISSUE TITLE
人脸检测结果是否能获得角度？

### ISSUE THREAD

**Issue by biduan** [ShiqiYu/libfacedetection#56]
于老师：
目前例子中得代码
int angle = p[5];
我理解是人脸得角度比如侧脸90度，但实际测试结果一直为0。

那是否可以获得人脸得角度？

**Comment by 774252326** [comment]
貌似只有facedetect_multiview和facedetect_multiview_reinforce能给出角度，而且都不准。
正对摄像头时给的结果在正负一二十度之间跳动。

**Comment by luckymingjia** [comment]
同样的问题，希望另两个函数也能输出角度值。

**Comment by takenhuang** [comment]
同上。
