### ISSUE TITLE
CNN版本無法執行

### ISSUE THREAD

**Issue by tonyasic** [ShiqiYu/libfacedetection#60]
于老師好:
Q1:試了CNN版本的face detection. compile time is OK! but run time error & quite! (非CNN版本x86 and x64皆正常)
Q2:可否提供win32 32bits CNN face detection .dll?
Thank u!
tonyasic

**Comment by ShiqiYu** [comment]
What's the error message?

**Comment by tonyasic** [comment]
Error message pop up  : "The application was unable to start correctly (0xc000001d)"

**Comment by tonyasic** [comment]
現在可以run到facedetect_cnn();(2018/10/20 code) 但是進入facedetect_cnn();後就沒有return了!
BTW: I'd download/update all code to 2018/10/20.

**Comment by ShiqiYu** [comment]
Does your CPU support Intel AVX?

**Comment by tonyasic** [comment]
No, my CPU(i5 750) doesn't support AVX. The key is AVX. Thanks for your kindly support. 
Can u provide SSE2 version dll for evaluation?
Thanks!
tonyasic

**Comment by ShiqiYu** [comment]
The speed of sse2 is not fast enough. Maybe later, but noy now.

tonyasic <notifications@github.com>于2018年10月23日 周二02:42写道：
