### ISSUE TITLE
请问于老师。bin里的so库可以用于android平台的开发么

### ISSUE THREAD

**Issue by liujilong0116** [ShiqiYu/libfacedetection#64]
于老师您好 我现在像将一段用到了您的库的代码移植到andriod平台 但是遇到了一系列问题 请问bin文件夹里的so库可以直接用于做android的开发么

**Comment by ShiqiYu** [comment]
应该不能。

liujilong0116 <notifications@github.com>于2018年11月8日 周四08:50写道：

**Comment by liujilong0116** [comment]
那请问于老师。 bin里的so库是设计用于什么的呢。麻烦老师了

**Comment by liujilong0116** [comment]
请问于老师   这个so是专门为linux准备的么

**Comment by ShiqiYu** [comment]
海思Hi35xx平台

**Comment by liujilong0116** [comment]
谢谢于老师的耐心解答

**Comment by sunjunlishi** [comment]
你好于老师，windows 有使用次数和时间的限制吗？感觉速度和效果都不错。

**Comment by ShiqiYu** [comment]
没有

liujilong0116 <notifications@github.com>于2018年11月8日 周四10:01写道：

**Comment by sunjunlishi** [comment]
太棒了。于老师的算法是为嵌入式门锁类人脸识别而生。
