### ISSUE TITLE
部分人脸框偏右

### ISSUE THREAD

**Issue by takenhuang** [ShiqiYu/libfacedetection#67]
![1](https://user-images.githubusercontent.com/43564483/49155320-9d33fd80-f355-11e8-9f23-67ba1d167a8f.png)
![2](https://user-images.githubusercontent.com/43564483/49155321-9dcc9400-f355-11e8-8d9f-4598a01e9feb.png)
![3](https://user-images.githubusercontent.com/43564483/49155323-9dcc9400-f355-11e8-9dc7-f6ccd203d4d2.png)
![4](https://user-images.githubusercontent.com/43564483/49155325-9e652a80-f355-11e8-99e1-0d72b60469ec.png)

**Comment by ShiqiYu** [comment]
If you resize the image to a multiple of 64 (at least a multiple of 32), it
will better.

**Comment by takenhuang** [comment]
尝试32倍数，有改善。

**Comment by JiaoPaner** [comment]
@takenhuang 您好 请问部分人脸框偏右 您解决了吗 能否给个示例 感谢

**Comment by ShiqiYu** [comment]
输入图像的宽度和高度建议用64的倍数，至少320的倍数，这样就不会偏移了。

**Comment by ShiqiYu** [comment]
输入图像的宽度和高度建议用64的倍数，至少32的倍数，这样就不会偏移了。
