### ISSUE TITLE
公司机器不行,家里机可以

### ISSUE THREAD

**Issue by fengxiatao** [ShiqiYu/libfacedetection#68]

**Comment by fengxiatao** [comment]
![qq 20181201110451](https://user-images.githubusercontent.com/14970645/49323656-b73e2d80-f559-11e8-827c-ccab33aab216.png)

**Comment by fengxiatao** [comment]
系统和VS2015完全一样、项目都是控制台程序一个源文件用老师您的例子

**Comment by ShiqiYu** [comment]
You CPU should support AVX2 for using the lib.

**Comment by fengxiatao** [comment]
老师您好，请问是我CPU不支持AVX2还是说，我电脑bios里面没有开启呀

**Comment by fengxiatao** [comment]
都是I5啊，新旧型号竟然有质的区别吗

**Comment by fengxiatao** [comment]
请问老师，这个有解决方法吗

**Comment by xzyaoi** [comment]
@fengxiatao 只有一部分的i5 CPU支持AVX2。如果你的CPU是4代之前的（即i5-3xxx），它们基本上是不支持AVX2的。详细的支持AVX2的CPU的列表可以在[https://en.wikipedia.org/wiki/Haswell_(microarchitecture)](https://en.wikipedia.org/wiki/Haswell_(microarchitecture))找到。
