### ISSUE TITLE
请问如何购买LINUX版本

### ISSUE THREAD

**Issue by fengxiatao** [ShiqiYu/libfacedetection#69]

**Comment by fengxiatao** [comment]
听说linux版本需要购买，请问如何购买和价格是怎么样的，英文水平不行，有中文方面的文档或者网页吗

**Comment by ShiqiYu** [comment]
We may release the source code in 2 months.

**Comment by WangMingyuan** [comment]
在win上测试 效果挺好  希望能在移动平台用起来

**Comment by richxnh** [comment]
非常期待，更多是在linux平台中使用

**Comment by ShiqiYu** [comment]
The face detection based on SSD/CNN is also good enough, much better than
AdaBoost, but not as good as mine.

**Comment by ShiqiYu** [comment]
The face detection based on SSD/CNN in OpenCV is also good enough, much
better than AdaBoost, but not as good as mine.

**Comment by huuson235** [comment]
Wish you release the source code after the Lunar new year holiday.

**Comment by ashuezy** [comment]
@ShiqiYu 
Waiting for the source code...
I would like to make improvements and train it on my own dataset.

**Comment by benjiaxu** [comment]
@ShiqiYu 
等待源代码
非常期待

**Comment by datagridview** [comment]
Waiting for the linux code, thanks for your giving.
