### ISSUE TITLE
不是人脸也剪切出来

### ISSUE THREAD

**Issue by fengxiatao** [ShiqiYu/libfacedetection#72]
pResults = facedetect_cnn(pBuffer, (unsigned char*)(image.ptr(0)), image.cols, image.rows, (int)image.step);
		printf("%d faces detected.\n", (pResults ? *pResults : 0));
		Mat result_cnn = image.clone();
		for (int i = 0; i < (pResults ? *pResults : 0); i++)
		{
			short * p = ((short*)(pResults + 1)) + 142 * i;
			int x = p[0];
			int y = p[1];
			int w = p[2];
			int h = p[3];
			int neighbors = p[4];
			int angle = p[5];
			printf("face_rect=[%d, %d, %d, %d], neighbors=%d, angle=%d\n", x, y, w, h, neighbors, angle);
			Rect_<float> face_rect = Rect_<float>(x, y, w, h);
			try {
				face = image(face_rect);
				imshow("view1", face);

**Comment by fengxiatao** [comment]
显示的不是人脸也出来啊，这是什么原因啊

**Comment by eagle-dai** [comment]
false positive，可以通过 neighbors 值过滤一部分

**Comment by Shea123** [comment]
我也遇到了，我对视频抽帧识别，不是人脸的物体也识别成人脸了
