### ISSUE TITLE
您好，于老师，为何新版没有人脸关键点检测？

### ISSUE THREAD

**Issue by vic9527** [ShiqiYu/libfacedetection#73]
您好，于老师，为何新版没有人脸关键点检测？
我看函数里面也没有是否需要人脸关键点检测的flag，请问是目前还不支持么？
![image](https://user-images.githubusercontent.com/9958494/49491368-d2c57300-f88e-11e8-80af-0da6e812abad.png)

**Comment by ShiqiYu** [comment]
We removed it, may added a CNN based one later.

If you want the previous version, you can download from GitHub at
https://github.com/ShiqiYu/libfacedetection/tree/2f6cbebd12ae9491b97675d86afd446f1d7d3426

**Comment by CharlieXie** [comment]
Thanks for your contribution to open source. I've learned a lot from this lib. How it's going on the plan which adds facial landmark to this lib?
