### ISSUE TITLE
Low accuracy on Video

### ISSUE THREAD

**Issue by ashuezy** [ShiqiYu/libfacedetection#74]
Hi,

Just tried your new CNN face detector on a sample CCTV video.
It is giving plenty of false positives. Also angle is not available anymore.

Good work never the less.

Regards,
xxx

**Comment by ShiqiYu** [comment]
If possible, you can upload a sample image that the algorithm cannot detect faces.

**Comment by deimsdeutsch** [comment]
accuracy is really terrible !

![image](https://user-images.githubusercontent.com/39468654/51679137-1a9d8680-2004-11e9-8a9c-cf4ef6cfe51b.png)

**Comment by ashuezy** [comment]
Yes... ears, eyes, trees, shadow, shirt, bag, bottle !
You name it ...it is detecting everything as a face.

**Comment by universeroc** [comment]
> accuracy is really terrible !
> 
> ![image](https://user-images.githubusercontent.com/39468654/51679137-1a9d8680-2004-11e9-8a9c-cf4ef6cfe51b.png)

Just check it's confidence (in code named neighbors), you can set a threshold to deal with it, may it help you

**Comment by universeroc** [comment]
> Yes... ears, eyes, trees, shadow, shirt, bag, bottle !
> You name it ...it is detecting everything as a face.

Just check it's confidence (in code named neighbors), you can set a threshold to deal with it, may it help you
