### ISSUE TITLE
CNN版本报错

### ISSUE THREAD

**Issue by smartzzy** [ShiqiYu/libfacedetection#76]
您好，于老师，我下载了您的人脸识别库，用VS2015编译运行后报错，错误提示是：
0x00007FF88EB04104 (libfacedetectcnn-x64.dll) (FaceDetect.exe 中)处有未经处理的异常: 0xC000001D: Illegal Instruction。
这是什么原因啊，我查了下我的CPU支持AVX，这是什么原因啊。

**Comment by ShiqiYu** [comment]
需要AVX2

**Comment by smartzzy** [comment]
谢谢老师，我找了台支持ＡＶＸ２的就可以啦，效果很好，谢谢
