### ISSUE TITLE
使用vs2015编译出错

### ISSUE THREAD

**Issue by job2003** [ShiqiYu/libfacedetection#83]
使用vs2015编译，出现如下错误
1>  facedetectcnn.cpp
1>d:\workspace\workspace_vs\facedetect\facedetect\facedetectcnn.cpp(120): error C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换
1>d:\workspace\workspace_vs\facedetect\facedetect\facedetectcnn.cpp(121): error C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换
1>d:\workspace\workspace_vs\facedetect\facedetect\facedetectcnn.cpp(982): error C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换
1>d:\workspace\workspace_vs\facedetect\facedetect\facedetectcnn.cpp(983): error C2676: 二进制“[”:“__m256”不定义该运算符或到预定义运算符可接收的类型的转换

**Comment by lrain-CN** [comment]
有个windows宏定义

**Comment by Cluoyao** [comment]
facedetectioncnn.cpp文件里面有宏定义__WIN__ 或者_WINDOWS，你把这两个中的的一个添加到: 属性->C/C++->预处理器->预处理器定义，这样就能运行了

**Comment by lrain-CN** [comment]
> 
> 
> facedetectioncnn.cpp文件里面有宏定义__WIN__ 或者_WINDOWS，你把这两个中的的一个添加到: 属性->C/C++->预处理器->预处理器定义，这样就能运行了

你测试这版的检测有误检吗， 我这边测试挺多误检，而且Windows下640的输入大概耗时在150ms（CPU i5-4590 3.3GHZ）

**Comment by ShiqiYu** [comment]
每个结果框都有一个可行度值，把低可信度的去掉就可以了。

**Comment by job2003** [comment]
已解决，谢谢。

**Comment by job2003** [comment]
已解决，谢谢。

**Comment by DCore-2046** [comment]
vs2015测试， 缺少一些库文章 gst.h glib.h

**Comment by DCore-2046** [comment]
vs2015测试， 缺少一些库文件 gst.h glib.h
