### ISSUE TITLE
[How to run caffe?]

### ISSUE THREAD

**Issue by HongChow** [ShiqiYu/libfacedetection#84]
hi Teacher Yu,
     The running result of pycaffe(using prototxt and caffe model in your repo) is different with c++ code(c++ code runs successfully detecting faces ). 
     I guess the reason is the lack of proper preprocessing?
    So, would you please tell me how to run it with pycaffe? 
    Any suggestion and instruction is greatly welcome. 
    Thanks you a lot.

**Comment by ShiqiYu** [comment]
Sorry I have no experience on pycaffe
