### ISSUE TITLE
修改最小人脸尺寸

### ISSUE THREAD

**Issue by hehohoku** [ShiqiYu/libfacedetection#85]
于老师，能否修改最小检测人脸尺寸，如何修改？谢谢

**Comment by ShiqiYu** [comment]
by resizing the size of the input image.

**Comment by hehohoku** [comment]
谢谢您的回复！
但是能否修改检测最小人脸尺寸，如现在是12*12，能否修改这个值？

**Comment by xuanyuyt** [comment]
最小尺度是根据你的训练样本中目标大小分布来的，如果你需要检测出更小尺度自然是要拿自己的数据去重新训练的。

**Comment by hehohoku** [comment]
谢谢！！！

**Comment by JoJo-ops** [comment]
> 最小尺度是根据你的训练样本中目标大小分布来的，如果你需要检测出更小尺度自然是要拿自己的数据去重新训练的。

怎么拿自己数据训练
