### ISSUE TITLE
file failed to open for writing (No such file or directory):

### ISSUE THREAD

**Issue by wyfSunflower** [ShiqiYu/libfacedetection#87]
(venv) gml@gml-TM1701:/media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection$ sudo mkdir build; cd build; cmake ..;make -j8;sudo make install
CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:174 (file):
  file failed to open for writing (No such file or directory):

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: Could not open file for write in copy operation /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdC
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (No such file or directory):

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (No such file or directory):

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

-- The C compiler identification is unknown
CMake Error: Could not open file for write in copy operation /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CMakeCCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:192 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: Could not find cmake module file: /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CMakeCCompiler.cmake
CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CompilerIdCXX
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (No such file or directory):

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (No such file or directory):

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

-- The CXX compiler identification is unknown
CMake Error: Could not open file for write in copy operation /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CMakeCXXCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:190 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: Could not find cmake module file: /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/3.13.1/CMakeCXXCompiler.cmake
-- Check for working C compiler: /usr/bin/cc
CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:25 (file):
  file failed to open for writing (No such file or directory):

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeTmp/testCCompiler.c
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
  Unknown extension ".c" for file

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeTmp/testCCompiler.c

  try_compile() works only for enabled languages.  Currently these are:

    C CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:48 (file):
  file failed to open for writing (No such file or directory):

    /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error at /opt/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
CMake Error: Cannot open file for write: /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /media/gml/8dafbd66-4140-4d3a-987f-e1819d41a64e/workspace/libfacedetection/build/CMakeCache.txt
CMake Error: : System Error: Permission denied
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

**Comment by novioleo** [comment]
权限没对应
