### ISSUE TITLE
Why is this library a binary?

### ISSUE THREAD

**Issue by patricksnape** [ShiqiYu/libfacedetection#9]
This isn't very useful for non-Windows 32-bit users, and doesn't represent open source code since this is actually a binary release. Why would you not provide the code that you used to create the lib? For example, I don't use Windows and so I cannot use this library!

**Comment by haotians** [comment]
second

**Comment by ShiYw** [comment]
Here's the thing:
we, users, simply wanna use it on Linux,but the binary file is hard to handle.
You've done a good job, but how can we use it?
Perhaps, you are worrying about others' copying, but at least, offer us the .so lib as well.

**Comment by willard-yuan** [comment]
I can't agree with above any more.

**Comment by ShiqiYu** [comment]
Because it is!

**Comment by LiuZhe1** [comment]
how can I get the source code?how much is it?
