### ISSUE TITLE
Error parsing text-format caffe.NetParameter: 813:14: Message type "caffe.LayerParameter" has no field named "norm_param".

### ISSUE THREAD

**Issue by goodhope258** [ShiqiYu/libfacedetection#92]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0315 13:06:33.427579 26834 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0315 13:06:33.427621 26834 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0315 13:06:33.427628 26834 _caffe.cpp:142] Net('/opt/libfacedetection/models/caffe/yufacedetectnet-open-v1.prototxt', 1, weights='/opt/libfacedetection/models/caffe/yufacedetectnet-open-v1.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 813:14: Message type "caffe.LayerParameter" has no field named "norm_param".
F0315 13:06:33.432250 26834 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /opt/libfacedetection/models/caffe/yufacedetectnet-open-v1.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by goodhope258** [comment]
/opt/libfacedetection/models/caffe$ /usr/bin/python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
>>> caffe.__version__
'1.0.0'

**Comment by GP1390** [comment]
the same problem

**Comment by xuanyuyt** [comment]
You need change your caffe version to SSD

**Comment by ShiqiYu** [comment]
Please use NVidia Caffe which supports SSD.

xuanyuyt <notifications@github.com>于2019年3月16日 周六22:58写道：
