### ISSUE TITLE
Is there any plan to open source tranditional face detection approach

### ISSUE THREAD

**Issue by chibai** [ShiqiYu/libfacedetection#98]
Dear Professor Yu:
    I've been watched the project for over 3 years. And I'm really happy and grateful that you can open source your code to make great contribution of the community. 
  As far as I knew, at the very beginning of the project, you are actually using pure c with traditional approach (perhaps V-J approach?) for face detection, which I think I can really learn a lot from the pure c code, cause it's so fast that there must be many speed-up tricks.
   I wish you could open source the traditional-approach face detection code. It really doesn't matter the dl approache is faster than traditional approach, I'm just so respecting the tricks of the code may used,.
    Best Wishes!

**Comment by ShiqiYu** [comment]
Sorry I cannot release the AdaBoost based face detection algorithm because
of some issues.

**Comment by jamessmith90** [comment]
@chibai 
Don't give me him any credit he has just copied the LBP algorithm which works on integers that is why it works fast. The real accuracy comes from the dataset and the traditional approach is not accurate enough to be used in production environment. Just train the wider face on MTCNN or on Yolov3-Tiny you will be surprised how good results you will get.

**Comment by ShiqiYu** [comment]
> @chibai
> Don't give him any credit he has just copied the LBP algorithm which works on integers that is why it works fast. The real accuracy comes from the dataset and the traditional approach is not accurate enough to be used in production environment. Just train the wider face on MTCNN or on Yolov3-Tiny you will be surprised how good results you will get.

The last part of your comments is partly correct.
